### ISSUE TITLE
Last tasks for deployment

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#101]
* [x] Set up Travis / GH releases, in order to make deployment easier. I guess we would bump the version in the cabal file and push a tag to GitHub every time we wanted to deploy, Travis would build it, and upload the result to a GitHub release, and then it would be uploaded to the server manually by @paf31?
* [x] Release version 0.7.1 of the compiler, which will include the fix in purescript/purescript#1221 (transitive dependencies were not being included in `psc-publish` output, resulting in links not being rendered).
* ~~Delete all the data on `new-pursuit` and regenerate it using `psc-publish` 0.7.1, for the same reason.~~ Since most of the libraries will probably get updated soon, this doesn't seem worth doing right now.
* [x] Perhaps we should also configure the production deployment to reject packages created by `psc-publish` 0.7.0?
* [x] Configure `Content-Security-Policy` headers on nginx. We get CSS and fonts from google, and there's also Google Analytics which you can turn on by putting a code into the environment variable `PURSUIT_GOOGLE_ANALYTICS_CODE`. Other than that we can block pretty much everything. I think this would work (newlines added for readability):

```
Content-Security-Policy:
default-src 'none';
script-src 'self' google-analytics.com;
style-src 'self' fonts.googleapis.com;
font-src fonts.gstatic.com;
img-src *;
connect-src 'self'; # for the version selector
plugin-types 'none';
base-uri 'none';
```

**Comment by hdgarrood** [comment]
That CSP header is almost what we want; see the one I committed instead.

**Comment by paf31** [comment]
I wouldn't worry about existing data. Those libraries will probably get updated soon anyway.

**Comment by paf31** [comment]
I've put the CSP header in place, but I still think we should consider redacting any custom HTML from the processed Markdown.

**Comment by hdgarrood** [comment]
Sounds good. I'll do that once the license is sorted out.

**Comment by hdgarrood** [comment]
The licence is sorted. Unfortunately not all of the libraries used a file called LICENSE for the information, so the generator script had to have a bunch of special cases.

ALSO, the two LGPL packages (cpphs, polyparse) have exceptions to the LGPL: https://github.com/purescript/pursuit/blob/8095503504155f85084d233e20765f9850dc7c35/LICENSE#L1772-L1778 and so I think it's fine to distribute binaries as long as we include the LICENSE file.

**Comment by hdgarrood** [comment]
Last thing and then this can be closed and we can switch the subdomains over: fix the Content-Security-Policy header. This is what new-pursuit currently looks like on Firefox: 
![either](https://cloud.githubusercontent.com/assets/1270186/8695567/a0242e8c-2add-11e5-9a43-2169abe799b0.png)
If you run `curl -i` you can see that the header that is being served contains lots of newline characters:
```
Content-Security-Policy: default-src 'none';
                script-src 'self' *.google-analytics.com;
                style-src 'self' fonts.googleapis.com;
                font-src fonts.gstatic.com;
                img-src *;
                connect-src 'self';
                plugin-types 'none';
                base-uri 'none'
```
I am 99% sure that this is the cause.
