### ISSUE TITLE
Use shields.io for badges

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#102]
I can't quite work out what it is, but the badges that pursuit currently renders just don't quite look right. Eg: http://new-pursuit.purescript.org/packages/purescript-thermite/0.8.0

**Comment by paf31** [comment]
Serif font? :)

**Comment by hdgarrood** [comment]
This is what it looks like on my machine:
![badge](https://cloud.githubusercontent.com/assets/1270186/8572446/8c247de6-2584-11e5-9d73-d12ac0a7b29e.png)
Half of the "p" is cut off on the left but there's more to it than that. I think shields.io ones have shadowing and maybe a slight convex effect?

Anyway since we're using shields.io for most of the other ones, I think it makes more sense to use shields.io for pursuit rather than try to make the pursuit ones imitate the shields ones. I suggest we make pursuit respond to `/packages/$PACKAGE/badge` with redirects to `https://img.shields.io/badge/pursuit-$VERSION-ee2255.svg`

**Comment by paf31** [comment]
Can we figure out the issue with the generated SVG? If we can produce one working badge, we should be able to fix them all, right?

**Comment by hdgarrood** [comment]
Yeah. I guess I could just look at the markup that shields.io produces and imitate that with little effort. Would you rather have Pursuit serve the SVG then?

**Comment by paf31** [comment]
I think we should do what's simplest, as long as we don't violate any TOS for shields.io.

**Comment by hdgarrood** [comment]
I didn't see any TOS, but it does seem that shields.io intends you to be able to fiddle with things in the way we're discussing. For example:
* https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md
* https://github.com/badges/shields/blob/master/templates/flat-template.svg
* https://github.com/h5bp/lazyweb-requests/issues/150

It looks like their server uses Cairo to determine what the width and height should be, see: https://github.com/badges/shields/blob/master/badge.js. I don't really want to do the same on the Pursuit server, that feels yucky. I guess we could choose fixed values rather than measuring text width on a canvas though; the left hand side is always the same, because it's just "pursuit", and the right hand side has a fairly narrow range of possible values, so we can probably come up with an accurate enough heuristic for that.

Using a redirect seems simpler, though.
