### ISSUE TITLE
Add title attributes to code links with fully qualified names

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#104]
Particularly useful when names collide, eg in Data.Sequence.NonEmpty:
![fqcn](https://cloud.githubusercontent.com/assets/1270186/8586815/317efdf0-25eb-11e5-970d-498b69b09cd8.png)

**Comment by paf31** [comment]
:+1:

**Comment by michaelficarra** [comment]
Yes, this would be great!
