### ISSUE TITLE
Require package uploaders to be repo contributors?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#105]
At the moment, anyone can upload anything, you only have to be signed in via GitHub. Perhaps only repo contributors should be able to upload packages?

**Comment by aspidites** [comment]
It's convenient for me to be able to upload documentation for a package that I'm learning that hasn't yet made it to pursuit. 

I don't do so if a tag doesnt exist.

**Comment by hdgarrood** [comment]
Closing this as it doesn't seem important; we can consider this again later if need be.
