### ISSUE TITLE
Better layout for mobile / tablet / anything else

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#107]
At the moment, the layout doesn't work very well on anything with a screen less than 1060px wide.

**Comment by paf31** [comment]
I was able to get something decent working using Bootstrap FWIW.

**Comment by hdgarrood** [comment]
I'm hoping that this will only be a case of a couple of media queries and other small tweaks to paddings and margins. I'd rather try it without using Bootstrap first; if it does turn out to be difficult then Bootstrap sounds like a good alternative option.

**Comment by paf31** [comment]
Agreed, if we can do without it, let's.
