### ISSUE TITLE
Locking to avoid multiple concurrent Hoogle DB regens

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#108]
At the moment, we could theoretically have many Hoogle database regenerations happening concurrently, as any search request that happens during a regeneration will trigger another one.

Some kind of locking mechanism (an `MVar ()` in the App data type, perhaps?) could help avoid this.

I think we should perhaps wait until this is causing issues on the server before actually implementing this, though. Currently, regeneration only takes around 5 seconds. When we switch to Hoogle 5, it should be even faster, as we will be able to avoid a `String` roundtrip.

**Comment by paf31** [comment]
Why is it that a search triggers a regen right now?

I think an `MVar` sounds fine if we can't avoid regenerating the DB.

**Comment by hdgarrood** [comment]
A request to `/search` will trigger a regen iff the last regen happened more than `PURSUIT_HOOGLE_DATABASE_MAX_AGE_SECONDS` ago (or whatever the variable name is). If that is the case, the `/search` handler forks a thread which regenerates the database and updates the database variable when it's done. In the meantime, any other requests to `/search` will cause more regeneration threads to be forked.

Here's the relevant code: https://github.com/purescript/pursuit/blob/01ad120f514670b92a7377f80920bcc5e4ddfd54/src/Handler/Hoogle.hs#L66-L82

**Comment by hdgarrood** [comment]
An alternative solution would be to fork a thread at startup that just does `forever (regenDB >> sleep databaseRegenInterval)`.
