### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#109]
See also purescript/purescript.github.io#21

**Comment by danse** [comment]
:+1: 

I think that this is even more important here, because the Pursuit page is a search engine. I use to keep it opened and pinned together with other pages useful when developing, and the icon is the only way one can distinguish them

**Comment by texastoland** [comment]
If you tell me what to do with it I can PR.

**Comment by danse** [comment]
:raised_hands:
