### ISSUE TITLE
Fragments to type class members and data constructors don't work

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#110]
For example, try clicking on the first result in http://new-pursuit.purescript.org/search?q=bind

One way of fixing this could be to make them point to the parent type class / data declaration instead. The only place where these links currently appear (as far as I'm aware) is in Hoogle results, and it's not currently obvious how to implement this. Perhaps it will be easier once we're using Hoogle 5. Alternatively, we could give each type class member / data constructor its own id attribute.

**Comment by paf31** [comment]
Would it make sense to add an anchor to the `li` element under "Members"?

**Comment by hdgarrood** [comment]
Yes, I think so. I think we'd need to do something with the CSS too, because it looks a bit odd currently if you add an anchor to those and then add it as a URL fragment.

**Comment by hdgarrood** [comment]
This appears a teensy bit harder than I first thought: we can't give the same `id` attribute to two different things. For example: the `Free` data type also has a constructor called `Free`. We could also have a case where a package declared a type synonym `Foo` and also a data constructor for a separate value `Foo`.

I think the solution should be to distinguish types and values in the anchors. Currently everything is `#d:Just` or `#d:Maybe` or whatever. We know that type names and value names are unique per module, so it should be sufficient to distinguish only these two cases; I suggest we copy Hackage by using eg `#v:Just` or `#v:maybe` for values, and `#t:Maybe` for types.

**Comment by michaelficarra** [comment]
:+1: They *are* separate namespaces, after all.
