### ISSUE TITLE
README not appearing for purescript-arrays

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#116]
See http://pursuit.purescript.org/packages/purescript-arrays/0.4.0

My best guess as to the cause is GitHub rate limiting. We could wait to see: if it works tomorrow, then I think we can safely assume that rate limiting was the cause.

**Comment by paf31** [comment]
Don't we cache readme files? (Sorry I feel like I've asked this before)

**Comment by michaelficarra** [comment]
I don't understand, it looks like it's working for me.

**Comment by paf31** [comment]
Same here, but it was offline earlier.

**Comment by hdgarrood** [comment]
We should be caching readme files, yeah. But if that page was only requested after the rate limit was reached that would explain it having been unavailable earlier. I expect the logs would contain an explanation too, come to think of it.

There's an optional environment variable for a github token, which gets used for fetching readmes. Is that set on the production server? Unauthenticated requests have a low rate limit, so setting that would probably stop this from happening.

**Comment by hdgarrood** [comment]
It might be worth checking data/cache/packages/purescript-arrays/0.4.0/index.html exists too.

**Comment by paf31** [comment]
No, it's not cached, but everything else is. No errors that I can see in the log.

**Comment by hdgarrood** [comment]
Weird, it should be writing data/cache/packages/$package/$version/index.html. Does the filename above appear in the log at all?

**Comment by hdgarrood** [comment]
This was fixed at the same time as #154
