### ISSUE TITLE
Searching by type is too general

### ISSUE THREAD

**Issue by Thimoteus** [purescript/pursuit#132]
Suppose I want to find a function with type signature Char -> String, but I don't know if it's called toString or fromChar or something else. If I search for `Char -> String` in pursuit, it doesn't show -- in fact, the second result is unsafeCoerce.

**Comment by hdgarrood** [comment]
Still appears to be an issue after #235. `Data.String.singleton` is the 10th result for the query `Char -> String`; arguably it should be the first.

**Comment by hdgarrood** [comment]
Fixed by @matthewleon in #286 - thanks!
