### ISSUE TITLE
Broken source links for packages produced on Windows

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#144]
http://pursuit.purescript.org/packages/purescript-either/0.2.1/docs/Data.Either.Unsafe#d:fromRight

Not sure what's going on here.

**Comment by hdgarrood** [comment]
Source links seem to be broken throughout `either` and also `affjax`, which were both uploaded by @garyb (on Windows?). I think this might be another path separator issue :(

**Comment by hdgarrood** [comment]
Although, source links in `debug` do work. Hm.

**Comment by garyb** [comment]
:sob:

I uploaded a whole bunch of stuff yesterday, so it's probably all broken now. I think I made the `debug` package on my Mac, before the Windows stuff was working.

**Comment by hdgarrood** [comment]
I think that the bug is inside pursuit, not psc-publish, so hopefully I can fix it and nothing will need reuploading.

**Comment by garyb** [comment]
Do you have the raw uploaded files from psc-publish somewhere then? I can run off a new one if you need to look at what Windows produces.

**Comment by hdgarrood** [comment]
I don't have easy access to them, but I don't think it matters - I think we just need to handle `\` separators here: https://github.com/purescript/pursuit/blob/5167928c06660ba339de9cf917cafc398aa038a6/src/Model/DocsAsHtml.hs#L206
