### ISSUE TITLE
Ability to modify package metadata after upload

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#148]
Low priority, but I think it'd be good to be able to edit package metadata, especially after we support things like tags and descriptions.

**Comment by hdgarrood** [comment]
What metadata exactly? Also, is there a problem with fixing the metadata issue in the repository, replacing the previous tag, and then re-uploading to Pursuit?

**Comment by paf31** [comment]
No, if that works, I think that's better. I always assumed you'd get a "package already exists" error.
