### ISSUE TITLE
Large records are difficult to read

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#149]
For example: http://pursuit.purescript.org/packages/purescript-benchotron/3.0.1/docs/Benchotron.Core#t:BenchmarkF

I think we should consider starting a new line for each label / property in rows / records, in some cases at least.

**Comment by paf31** [comment]
I'd also like to start use `boxes` in the compiler for pretty printing types, on a related note.

**Comment by paf31** [comment]
Another example here

http://pursuit.purescript.org/packages/purescript-react/0.3.0/docs/React#t:ReactSpec

 :smile:

**Comment by hdgarrood** [comment]
refs purescript/purescript#1538

**Comment by hdgarrood** [comment]
I think this could reuse a lot of the code in a source code formatter, see https://github.com/purescript/roadmap/issues/23

**Comment by hdgarrood** [comment]
Since the relevant code is now in the compiler I'm going to close this in favour of https://github.com/purescript/purescript/issues/1538
