### ISSUE TITLE
If a search ends with a dot Pursuit will issue a 400

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/pursuit#153]
http://pursuit.purescript.org/search?q=Data.
![pursuit_err](https://cloud.githubusercontent.com/assets/6189397/10126346/a93b8aae-6590-11e5-9f2d-be2f28e45142.png)

This hurts us in https://github.com/kRITZCREEK/psc-ide/pull/70. Googling didn't bring up any special encoding for trailing dots in url parameters.

**Comment by hdgarrood** [comment]
Yeah, this is Hoogle-specific, it's because we're passing the query straight through to Hoogle. I'm hoping that this will just go away when we upgrade to Hoogle 5 (which hasn't been released yet).

**Comment by kRITZCREEK** [comment]
Seems to be fixed after the new search was implemented. I'll remove the workaround from `psc-ide` and close this afterwards.

**Comment by paf31** [comment]
Thanks @kRITZCREEK
