### ISSUE TITLE
Version numbers are not sorted properly

### ISSUE THREAD

**Issue by tfausak** [purescript/pursuit#156]
The version select box displays 0.0.10 below 0.0.2 and considers 0.0.9 the latest version.

![screen shot 2015-11-04 at 7 08 48 am](https://cloud.githubusercontent.com/assets/408753/10938894/475a2f02-82c3-11e5-91de-218c5facf3ee.png)

http://pursuit.purescript.org/packages/purescript-neon/0.0.10

However if I go to <http://pursuit.purescript.org/packages/purescript-neon>, it takes me to 0.0.10.

**Comment by hdgarrood** [comment]
Such type safety. Wow.

*hangs head in shame*

**Comment by tfausak** [comment]
To be fair, I think the problem is in JavaScript: https://github.com/purescript/pursuit/blob/aad2298/static/js/Pursuit.js#L43

**Comment by hdgarrood** [comment]
Yes, but there's a little more to it than that I think. The versions should have been sorted while they were still values of type `Version` on the server side, rather than `String`; that is, before being serialized. I already fixed it, see #157 :)

**Comment by tfausak** [comment]
:+1:
