### ISSUE TITLE
Tree-diagram of official purescript and purescript-contrib libs

### ISSUE THREAD

**Issue by michaelsbradleyjr** [purescript/pursuit#158]
It would be nice if the [pursuit.purescript.org](http://pursuit.purescript.org) website featured a tree-diagram (regularly refreshed) that visualized the dependency relationships of the various `purescript-???` libs associated with the [purescript](https://github.com/purescript/) and [purescript-contrib](https://github.com/purescript-contrib/) GitHub organizations. The colors of the nodes could differ for core vs. contrib libraries.

The idea is that it would make it a bit easier for newcomers to wade through code, "from the bottom up".

**Comment by hdgarrood** [comment]
I can certainly understand where you're coming from, but my experience is that in practice, any sort of attempt to graph software package dependencies ends up being a completely horrible mess which is impossible to obtain any useful information from.

Could you first perhaps explain the core problem that we would be trying to solve here? I'm not sure I fully get it. If you can think of any specific scenarios, I think that would help.

**Comment by michaelsbradleyjr** [comment]
Mainly, I was just looking for a "visual map" of the core purescript libs that would guide me as to knowing what builds on what, so as to have a preferred direction when reading the sources, starting with Purescript's Prelude.

**Comment by garyb** [comment]
This covers the core/contrib libraries and even has `tred` applied too, you can probably see the issue with it :wink:

![reduced](https://cloud.githubusercontent.com/assets/693642/11061487/6928df08-879f-11e5-8586-dc933924108c.png)

**Comment by michaelsbradleyjr** [comment]
I see your point. Maybe a dynamic chart, e.g. something built with purescript + d3.js, which allowed a viewer to expand and collapse branches as they went along, would work better.

Something like: http://bl.ocks.org/d3noob/8375092

I'm still working through the purescript book, but when I get to a point where I feel comfortable hacking on such a thing, I'll give it a shot.

**Comment by garyb** [comment]
Yeah that might be nice, it should be pretty easy to do too from the data side of things - I generated the above from data in `bower`, but we could probably maintain a JSON graph of the relations in pursuit.

**Comment by paf31** [comment]
I think such a thing might be neat as a visualization, just as something cool to put on the front page, or if we want to use it for navigation, I think we need to be careful to present it well, since there will be a lot of branching at the lower levels due to FFI libraries. It might be simpler to just add a "core" section to the front page, and perhaps a tool for finding reverse dependencies.

**Comment by hdgarrood** [comment]
I'm going to close this, partially because of how long it's been open but also because I don't see a reason that any dynamic chart as suggested here would need to be built in to pursuit.
