### ISSUE TITLE
Set Cache-Control header for badges

### ISSUE THREAD

**Issue by zudov** [purescript/pursuit#160]
Citing myself from https://github.com/fpco/stackage-server/pull/141

> Since [github proxies external resources](https://github.com/blog/743-sidejack-prevention-phase-3-ssl-proxied-assets) we need to indicate that our badges are supposed to be changing.

> From a brief study of https://github.com/atmos/camo it seems that unless we set something sensible in 'Cache-Control', the browser would be told to cache an image for a pretty long time.

> https://github.com/atmos/camo/blob/da97a43fc385c24abded595b3f278802eb23586b/server.coffee#L103

> Related: https://github.com/github/markup/issues/224

I observed this in effect today -- my browser was showing an outdated pursuit badge until I did "force refresh".

The patch should be [trivial](https://github.com/fpco/stackage-server/pull/141/files#r44915514) and is mostly about deciding what the ttl should be.

**Comment by hdgarrood** [comment]
I guess it ought to be Cache-Control: no-cache - it seems to me that it will be the case fairly often that people will look at badges immediately after the badges' state changes.

According to that github/markup issue we also need to be setting one of expires, etag, or last-modified. I vote expires with however you say "immediately" (a date in the past?)

**Comment by zudov** [comment]
`no-cache` seems a right idea.

It seems that we already have an `ETag`:
```shell
+zudov@x200 ~ $ curl -I http://pursuit.purescript.org/packages/purescript-strongcheck-generics/badge
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Mon, 16 Nov 2015 13:10:23 GMT
Content-Type: image/svg+xml
Content-Length: 676
Last-Modified: Thu, 12 Nov 2015 06:27:04 GMT
Connection: keep-alive
ETag: "56443138-2a4"
...
```

> I vote expires with however you say "immediately" (a date in the past?).

Yesod has a function which says "immediately" :D https://hackage.haskell.org/package/yesod-core-1.4.15.1/docs/Yesod-Core-Handler.html#v:alreadyExpired

**Comment by hdgarrood** [comment]
Didn't realize we already had etag, lol. In that case it probably makes sense to stick with etag and just add the cache-control header.

Because of the way we cache things, this needs to be done in the nginx configuration rather than the yesod application. Most requests don't ever reach the yesod application.

**Comment by zudov** [comment]
I see. Thanks.

**Comment by paf31** [comment]
Fixed, thanks.

```text
location ~* /badge$ {
        add_header Cache-Control "no-cache";
}
```
