### ISSUE TITLE
CSS text color not set

### ISSUE THREAD

**Issue by jplatte** [purescript/pursuit#164]
By default most browsers use black or maybe dark grey for this, but there is no guarantee for that.
I don't have it set that way because white on dark grey just looks a lot better than the default on html pages without CSS. This is not a hidden setting, it's accessible under Settings -> Content -> Colors.

![Screenshot](https://i.imgur.com/mSa7sCm.png)

**Comment by hdgarrood** [comment]
Wow, I'm surprised that changing that setting is actually workable. I would expect it to make most websites unusable! Anyway yes, I agree.
