### ISSUE TITLE
Fragment encoding issue with search results

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#166]
Repro steps:
* Search http://pursuit.purescript.org/search?q=footer%27
* Click on the first result

The fragment you get is `#v:footer-39-` but it should really be `#v:footer'` (or maybe we should percent-encode the `'`, I'm not quite sure).

**Comment by kseo** [comment]
#193 fixed this. Now we get the fragment `#v:footer'` correctly.

**Comment by hdgarrood** [comment]
Confirmed, thank you!
