### ISSUE TITLE
405 error when trying to publish via POST request

### ISSUE THREAD

**Issue by garyb** [purescript/pursuit#170]
I've set up a few repos recently to use the auto-publishing from Travis, and it seems to be rejecting submissions now - including on some repos where it has worked previously, so it's not just that I'm doing it wrong!

It worked here for v0.5.0: https://travis-ci.org/slamdata/purescript-css/builds/92320775
But failed today for v0.5.1: https://travis-ci.org/slamdata/purescript-css/builds/94373995

**Comment by hdgarrood** [comment]
Yeah, I've run into this before too. It just needs a small change to the nginx config, see https://github.com/purescript/pursuit/commit/5da82dcfad148fbe44db2773921489d244655733

**Comment by hdgarrood** [comment]
Specifically, it's because:

* I recently added the ability to `GET /packages; Accept: application/json` to get all the packages as JSON
* The caching system means that that response gets cached on the disk, under the nginx document root
* Now, nginx realises you're trying to POST to a file on the disk and it sends 405.

**Comment by garyb** [comment]
Ah okay. I'm an ignoramus when it comes to configuring nginx so I'll have to leave that one to you :smile:

**Comment by hdgarrood** [comment]
The only workaround I'm aware of is submitting packages manually, which still works.

**Comment by garyb** [comment]
Yeah, the reason I want this (aside from convenience) is I almost always forget to update Pursuit when releasing a package!

**Comment by garyb** [comment]
Maybe something like this would work? http://stackoverflow.com/a/26492897/139614

**Comment by hdgarrood** [comment]
I'm not really sure what's going on there; it's not obvious to me that that configuration should result in nginx proxying to the backend properly. However I did test https://github.com/purescript/pursuit/commit/5da82dcfad148fbe44db2773921489d244655733 locally and it worked.

**Comment by garyb** [comment]
Oh, sorry, I see - I hadn't realised that was the pending fix, I thought that was the change that caused it.

**Comment by hdgarrood** [comment]
It didn't occur to me that my previous comment could be read that way! Oops. :)

**Comment by garyb** [comment]
Oh yeah, now you're back @paf31, can you redeploy pursuit if you're happy with the nginx change here?

**Comment by paf31** [comment]
Yep, I'll look into this today.

**Comment by paf31** [comment]
Ok, Nginx is updated to include @hdgarrood's changes. I can upload packages from the website just fine, but can someone please try to reproduce the original error?

**Comment by garyb** [comment]
Whoop! :tada: It works again, thanks both.

**Comment by paf31** [comment]
So we can setup the core libraries to push to Pursuit when tagged now, correct?

**Comment by garyb** [comment]
Already started doing so (kinda, I'm working on Prelude updates, will open something for discussion in a bit)

**Comment by hdgarrood** [comment]
Yep, I think so. Personally I'm still undecided whether it would be
better to wait for pulp release (which is coming soon, honest!) but the
automatic route via CI definitely seems worth trying.

There's also an issue somewhere about adding psc-publish --dry-run to
the test suites, which should probably happen at the same time, especially if we're
setting travis up to automatically upload to pursuit when we tag.
