### ISSUE TITLE
"How to submit packages" section on Pursuit should have a section about submitting new versions of packages

### ISSUE THREAD

**Issue by cdepillabout** [purescript/pursuit#172]
It would be nice if there was a section on updating packages on Pursuit's [help](http://pursuit.purescript.org/help) page.

As a new user, when I want to update a package I've previously released, I'm not sure whether I need to upload a new `pursuit.json` file, or if I just need to push a new tag to Github (similar to how bower packages work).

It would be nice if there was a section on the help page explaining this.

**Comment by hdgarrood** [comment]
:+1: agreed. For now, the answer is yes, you do need to generate and upload a new `pursuit.json` file, in the exact same manner as before (except that you don't need to `bower register` again, of course).

**Comment by cdepillabout** [comment]
Sounds good.  Should I add it and send a pull request?

**Comment by hdgarrood** [comment]
Yes please.

**Comment by cdepillabout** [comment]
I submitted a pull request at #173.

I noticed two things while playing around with this.

1. It doesn't look like uploading from the command line is working?  Maybe this is fixed in commit cd9e1c1c2e?
2. The help page currently says the following:

    ```
    Ensure that the tagged version is checked out, change to your project directory, and run:
    
    $ psc-publish > pursuit.json
    
    This will go through your bower.json file and all of your code, collecting all of the information necessary to host your package on Pursuit, and dump that data to a new file called pursuit.json.
    ```

   This sounds good, but it doesn't seem to actually work.  When I follow the above steps, I get the following error:

    ```sh
    $ psc-publish --dry-run
    Dry run completed, no errors.
    $ psc-publish > pursuit.json
    There is a problem with your package, which meant that it could not be
    published.
    Details:
      Your git working tree is dirty. Please commit, discard, or stash your changes
      first.
    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    Untracked files:
      (use "git add <file>..." to include in what will be committed)
    
            pursuit.json
    
    nothing added to commit but untracked files present (use "git add" to track)
    ```

   I'm not sure what the best way is to fix this?  Maybe `psc-publish`  could ignore the `pursuit.json` file when checking if the working directory is dirty?  Or maybe `pulp` could add `pursuit.json` to the `.gitignore` by default?

**Comment by hdgarrood** [comment]
1. Yeah, see #170 
2. Ah yes, oops, that was written before we made a dirty working directory an error. I have actually seen a few `pursuit.json`s checked in, and people probably don't want that. Maybe adding it to the default `.gitignore` is a good idea. Anyway, before long, nobody will be using `psc-publish` directly anyway, see: bodil/pulp#57

**Comment by hdgarrood** [comment]
For now I suppose we can address this by suggesting you add `pursuit.json` to your `.gitignore` on this help page, especially since there are lots of existing projects which don't have it in there.

**Comment by cdepillabout** [comment]
Okay, sounds good.  Thanks!
