### ISSUE TITLE
Searching for '*>' results in parse error

### ISSUE THREAD

**Issue by EugeneN** [purescript/pursuit#175]
Search results: *>

Parse error 1:2: (line 1, column 2): unexpected ">" expecting letter

![screen shot 2015-12-12 at 7 46 59 pm](https://cloud.githubusercontent.com/assets/1272946/11763171/3328b666-a109-11e5-9808-bc2c0749c178.png)

**Comment by hdgarrood** [comment]
Ah. That's not ideal. What happens if you put parens around it?

**Comment by EugeneN** [comment]
With parens everything is ok: http://pursuit.purescript.org/search?q=%28*%3E%29 :-)
