### ISSUE TITLE
Constrained types without forall are incorrectly formatted

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#176]
E.g. <http://pursuit.purescript.org/packages/purescript-partial/1.0.0/docs/Partial.Unsafe#v:unsafePartial>

The `Partial => a` should all be inside parens.

This applies to `psc-docs` too.

**Comment by hdgarrood** [comment]
:scream:

**Comment by hdgarrood** [comment]
I guess that means this needs fixing inside the compiler, then.

**Comment by paf31** [comment]
I thought the formatting was done here? I think there is already an issue on the compiler anyway.

**Comment by hdgarrood** [comment]
Some of the formatting is done here, but I think the culprit is probably in Language.PureScript.Docs somewhere. By the time it reaches Pursuit it's already been converted to RenderedCode IIRC.

**Comment by hdgarrood** [comment]
Is https://github.com/purescript/purescript-partial/blob/325f4c9fce376b2ae6af99e7c22887f8094ca7f2/docs/Partial/Unsafe.md showing these correctly now? If so, I guess it must have been fixed inside the compiler. When we release 0.8, we can update Pursuit to use 0.8, and that should fix it here, too.

**Comment by hdgarrood** [comment]
Ah, just tried with `master` and it is still broken. I guess you must have fixed the markdown docs manually.
