### ISSUE TITLE
Badge urls give 404s

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#182]
Eg: https://pursuit.purescript.org/packages/purescript-prelude/badge

Maybe this is something to do with HTTPS? I'm not sure.

**Comment by tfausak** [comment]
I would like to be able to use Pursuit badges. What can I do to help resolve this?

I noticed that the 404 given by `/badge` is different than the site-wide 404 (like [this one](https://pursuit.purescript.org/packages/purescript-prelude/not-found)). What's up with that?

**Comment by hdgarrood** [comment]
I haven't found the time to look into this properly, so I'm not really sure. I suspect this is a bug in the code in this repo (as opposed to a configuration issue or whatever). The relevant modules would probably be Handler.Packages, config/routes, and Handler.PackageBadges. Also might help to get Pursuit running locally (let me know if you come across any difficulties), try to reproduce, and see if anything useful appears in the logs.

**Comment by hdgarrood** [comment]
Oops sorry, Handler.Packages isn't it. Also, all the 404s should have the pursuit header and footer, there shouldn't be any 404s from nginx. I think this might actually be an nginx config issue.

**Comment by tfausak** [comment]
The badge works locally. I see this in the logs:

```
30/Apr/2016:13:50:23 -0500 [Debug] writing response to disk for caching: ./data/cache/packages/purescript-prelude/badge/index.svg @(pursu_GQ0pTYJOPXH9BLb6f0aHDb:Handler.Caching src/Handler/Caching.hs:58:9)
GET /packages/purescript-prelude/badge
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  Status: 200 OK 0.001298s
```

Does that mean it's a problem with nginx?

**Comment by hdgarrood** [comment]
That would be my main suspicion now, yeah. The way the caching works is that the yesod app writes cacheable stuff to the disk while responding to requests, and nginx attempts to serve things from the disk first, and then forwards the request on to the yesod app if not. I'm not sure how that would lead to 404s though.

At this stage, I'd try to reproduce this locally by putting the yesod app behind an nginx instance. I think the nginx config file in config/ is up to date (ie, close enough to the production config to be able to reproduce this problem with), but I'm not 100% sure about this, maybe @paf31 can advise here.

**Comment by tfausak** [comment]
No luck firing up nginx.

```
> nginx -v
nginx version: nginx/1.10.0
> nginx -c $(pwd)/config/nginx.dev.conf
nginx: [emerg] "map" directive is not allowed here in /Users/taylor/Documents/Code/pursuit/config/nginx.dev.conf:3
```

**Comment by hdgarrood** [comment]
I would guess this indicates a version mismatch. I'm not sure which version the server is using (maybe it will tell you in response headers?)

**Comment by tfausak** [comment]
Production Pursuit says it's using nginx 1.4.6. 

I got the config working by adding an empty `events { }` section and wrapping everything else in `http { ... }`. Even with that setup I was still able to get the badge locally. (I also rebuilt and ran the server in production mode.)

**Comment by hdgarrood** [comment]
Ok, then I'm out of ideas, sorry. Perhaps there's something in the production nginx log?

**Comment by paf31** [comment]
It should be working now. Can you please confirm?

It seemed to be related to an issue with nested `location` blocks in the nginx config.

**Comment by tfausak** [comment]
👍 Works great!
