### ISSUE TITLE
Update to 0.8

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#183]
It shouldn't be too difficult to update to 0.8 I think. The only hard bit is that the JSON format changed.

I think we should do the following:
* Use https://github.com/hdgarrood/pursuit-check-missing to make a note of everything that's currently in pursuit. I'll have to modify it slightly to be able to do that, but that should be easy. (@hdgarrood)
* Deploy 0.3.0 (@paf31)
* Delete all the data on the server (@paf31)
* I'll then run that script again, and regenerate and upload everything using psc-publish from 0.8.0. (@hdgarrood)

I'll let you know once I've done the first step.

**Comment by hdgarrood** [comment]
Oh, also:

* Update the server configuration to require at least 0.8 for new uploads. That way, we get a better error if someone tries to upload with 0.7.x.

**Comment by hdgarrood** [comment]
Ok, step 1 is done: https://gist.github.com/hdgarrood/28f3d87e38f6b5b5c377

**Comment by paf31** [comment]
2 and 3 are done, and I've updated the minimum package version to 0.8.0.

**Comment by hdgarrood** [comment]
We're pretty much there now: https://www.reddit.com/r/purescript/comments/4414xe/announcement_re_migration_of_pursuit_to_080/

I'll try to diagnose the Hoogle issue locally.
