### ISSUE TITLE
Keep query in search field

### ISSUE THREAD

**Issue by AppShipIt** [purescript/pursuit#185]
As a user I'd like to edit my previously entered query in the search field after navigating to results 🙏

**Comment by hdgarrood** [comment]
:+1: as you pointed out on twitter, this could be useful for if you make a typo

**Comment by LiamGoodacre** [comment]
Hey, I'm having a go at this :smiley:
PR coming shortly.

**Comment by hdgarrood** [comment]
Fixed by #185. Thanks again @LiamGoodacre!
