### ISSUE TITLE
Language.PureScript.Names.Qualified of type Qualified expected Array but got String

### ISSUE THREAD

**Issue by brakmic** [purescript/pursuit#188]
Hi,

I get this error message immediately after clicking on Submit button. 

![aeson_fromjson](https://cloud.githubusercontent.com/assets/56779/12874798/d098cb30-cddb-11e5-91f2-ea0356603279.png)

I registered my package on bower (purescript-redux), created a proper tag (0.1.0) on GitHub and there was no problem with generating pursuit.json. 

I tried to upload it via Chrome and Firefox but failed with the same error.

Not sure if I'm doing something wrong.

**Comment by hdgarrood** [comment]
What version of the compiler are you using?

**Comment by brakmic** [comment]
0.8.0

**Comment by hdgarrood** [comment]
Ok - is that the proper 0.8 release, or the RC? Also could you post the JSON (on a gist or something?)

Finally, how did you install PureScript?

**Comment by brakmic** [comment]
This is what the console spits out when I enter psc --version: 0.8.0.0

I installed purescript globally via npm install -g and also locally for the project (also via npm).

Here's the Gist: https://gist.github.com/brakmic/5fdad8eea7eee4767897

**Comment by hdgarrood** [comment]
Unfortunately, the RC and 0.8.0 proper both say that.

You can check by trying the import syntax which was in the RC and was removed: import Prelude (..)

Also, when did you try to upload the package?

I'll look at the JSON later to try to work out what's happened.

**Comment by brakmic** [comment]
I have the release version because it throws an error when using (..).

![error](https://cloud.githubusercontent.com/assets/56779/12875484/e7bb1a38-cdeb-11e5-9e61-c49a8a18e61e.png)

I tried to upload the package 60-80 minutes ago.

**Comment by hdgarrood** [comment]
Are you sure you were using the same one when you ran `psc-publish`? Your package.json depends on `purescript` so that gulp task is probably using the locally installed one.

For me, when I tried to run `psc-publish` after cloning your repository, it failed because of https://github.com/purescript/purescript/issues/1834, which makes me think you were using the RC.

**Comment by hdgarrood** [comment]
Related: @paf31 / @garyb can we get a 0.8.1 out soon? Or even just release an 0.8.1 that's exactly the same as 0.8.0? The versions issue is turning out to be more irritating than I thought it would be.

**Comment by hdgarrood** [comment]
Yeah, I'm almost certain you were using the RC, because I just generated a pursuit.json file using `master` and tested uploading it to the Pursuit in my local dev environment and it worked. I'll just upload that to the real Pursuit for you, since that I've generated it already.

**Comment by hdgarrood** [comment]
https://pursuit.purescript.org/packages/purescript-redux/0.1.0

**Comment by brakmic** [comment]
Many thanks. :+1: 

I think the best 'solution' for me would be to re-install global & local psc's.

**Comment by brakmic** [comment]
Just to inform you that even after having re-installed everything the same problem appears (on another package I'd like to upload).

I installed psc locally & globally via 'npm install purescript@latest'.

I think it's much wiser to wait for the next release than to experiment around. Have not that much experience with the psc itself :smile: 

Many thanks & regards,

**Comment by hdgarrood** [comment]
Ah that's weird. What do you get if you run "where psc-publish"?

**Comment by brakmic** [comment]
```shell
D:\src\js\inferno\demo1>where psc-publish
C:\bin\purescript\psc-publish.exe
C:\Users\Harris\AppData\Roaming\npm\psc-publish
C:\Users\Harris\AppData\Roaming\npm\psc-publish.cmd
```

**Comment by brakmic** [comment]
Maybe this is the reason for such a weird behavior. The first path under c:\bin. 
It also shows psc 0.8.0.0 but I didn't update it previously.

I'll remove it and generate *pursuit.json* again.

**Comment by brakmic** [comment]
Now I get another error that should be posted at purescript/issues....should I open a new issue?

```shell
D:\src\purescript\purescript-ractive>psc-publish > pursuit.json
psc-publish.exe: An internal error ocurred during compilation: "Docs.Convert.ReExports: while collecting re-exports for module: Data.Foreign.EasyFFI, lookupValueDeclaration: unexpected result:\nother: []\nident: Ident \"unsafeForeignFunction\"\ndecls: [Declaration {declTitle = \"unsafeForeignProcedure\", declComments = Nothing, declSourceSpan = Just (SourceSpan {spanName = \"bower_components\\\\purescript-easy-ffi\\\\src\\\\EasyFFI.purs\", spanStart = SourcePos {sourcePosLine = 10, sourcePosColumn = 1}, spanEnd = SourcePos {sourcePosLine = 12, sourcePosColumn = 1}}), declChildren = [], declFixity = Nothing, declInfo = ValueDeclaration (ForAll \"a\" (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"Function\"}))) (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"Array\"}))) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"String\"}))))) (TypeApp (TypeApp (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"Function\"}))) (TypeConstructor (Qualified (Just (ModuleName [ProperName {runProperName = \"Prim\"}])) (ProperName {runProperName = \"String\"})))) (TypeVar \"a\"))) Nothing)}]"
Please report this at https://github.com/purescript/purescript/issues
```

**Comment by hdgarrood** [comment]
No, what you're seeing there is purescript/purescript#1834. You could work around it by adding some explicit type signatures to EasyFFI (I think unsafeForeignFunction is missing one) but the easiest solution is probably to wait for it to be fixed.

**Comment by brakmic** [comment]
Yeah, no problem. I'll wait. 

Thanks :+1:
