### ISSUE TITLE
Keep track of up-to-date libraries

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#192]
See https://github.com/purescript/roadmap/issues/34.

Ideally:
- Pursuit would keep track in its database of the set of compatible compiler versions for every version of every library.
- There would be an API to update this table at the end of a Travis build, authenticated using GitHub.
- Somewhere we'd have a list of libraries which are considered up to date, in the sense that they build with the latest compiler.

**Comment by hdgarrood** [comment]
Does it make sense to close this now that https://github.com/purescript/package-sets exists?

**Comment by paf31** [comment]
I think that once we have tools for curation of package sets, this will be solved. In particular, we need a way to check which libraries in the set have been updated, and to what version.

In any case, this no longer belongs here, so I'll close it.
