### ISSUE TITLE
Add a help page explaining the syntax of searches

### ISSUE THREAD

**Issue by kseo** [purescript/pursuit#198]
Pursuit (internally, Hoogle) provides a bunch of search options:
- map" Search for the text "map"
- "con map" Search for the text "map" and the text "con"
- "a -> a" Search for the type "a -> a"
- ":: a -> a" Search for the type "a -> a"
- "a" Search for the text "a"
- ":: a" Search for the type "a"
- "id :: a -> a" Search for the text "id" and the type "a -> a"

Adding a help page explaining these options would be helpful for users who do not have prior experience with Hoogle.

**Comment by hdgarrood** [comment]
:+1:

**Comment by hdgarrood** [comment]
Not having Hoogle changes this a bit, but also this is now subsumed by #339, so I'll close.
