### ISSUE TITLE
Sort versions on 'missing version' page

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#201]
eg: https://pursuit.purescript.org/packages/purescript-prelude/9.9.9/docs/Prelude

The relevant code is in `Handler.Packages`.

**Comment by paulyoung** [comment]
I'm not seeing this issue locally for some reason.

![screen shot 2016-03-29 at 1 28 56 pm](https://cloud.githubusercontent.com/assets/84700/14122844/52634200-f5b2-11e5-9b76-b59ee22da223.png)

**Comment by hdgarrood** [comment]
No, nor am I. But we shouldn't be making assumptions about the order of stuff returned by `getDirectoryContents` anyway, I think.

**Comment by paulyoung** [comment]
Looks like @stefanholzmueller has it covered anyway!

**Comment by hdgarrood** [comment]
Fixed by https://github.com/purescript/pursuit/commit/0c308d868f454e743035720eddfcc11db162fbc2. Thanks @stefanholzmueller!
