### ISSUE TITLE
Build/Linking fails on Windows

### ISSUE THREAD

**Issue by stefanholzmueller** [purescript/pursuit#203]
Tried to build the project with `stack build` after a `stack setup` on Windows 7. Came pretty far, but linking failed:

    [1 of 1] Compiling Main             ( app\main.hs, .stack-work\dist\2672c1f3\build\pursuit\pursuit-tmp\Main.o )
    Linking .stack-work\dist\2672c1f3\build\pursuit\pursuit.exe ...
    realgcc.exe: error: CreateProcess: No such file or directory
    Completed all 214 actions.
    
    --  While building package pursuit-0.3.5 using:
          C:\Users\bear\bin\stack-0.1.6.0\setup-exe-cache\setup-Simple-Cabal-1.22.5.0-x86_64-windows-ghc-7.10.3.exe --builddir=.stack-work\dist\2672c1f3\ build lib:
    pursuit exe:pursuit --ghc-options " -ddump-hi -ddump-to-file"
        Process exited with code: ExitFailure 1

According to Google, it could be related to limitations of the Windows command line.

**Comment by hdgarrood** [comment]
What happens if you run `where realgcc`? Maybe it's expecting `realgcc` to be on your PATH.

**Comment by hdgarrood** [comment]
Actually no, I think you're right, see https://github.com/commercialhaskell/stack/issues/795. Looking at that issue, it looks like GHC 7.10.3 includes a fix? What is the output of `stack exec ghc -- --version` if you run it inside the Pursuit directory?

**Comment by stefanholzmueller** [comment]
It says 7.10.3
I also read something about PATH, but adding the directory with `realgcc` in it did not help.
As a workaround, I am trying to move the pursuit directory up to C:\ *sigh*

**Comment by hdgarrood** [comment]
Ah, that's a shame. You might also consider running pursuit inside an Ubuntu VM? Vagrant seems to be a decent choice for that kind of stuff.

**Comment by stefanholzmueller** [comment]
Moving did not help either. I'm giving up on Windows. Yeah, guess I need a VM.

**Comment by hdgarrood** [comment]
Good luck!
