### ISSUE TITLE
Reliance on explicit type declarations

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#21]
Looking at `entriesForDeclaration` it seems that `pursuit-gen` only generates entries for values if they have explicit type declarations, since it only matches on `TypeDeclaration` and not `ValueDeclaration` (although I haven't managed to verify this yet).

Maybe it could perform type checking and then use inferred types instead, so that any values without explicit type signatures will show up?

**Comment by hdgarrood** [comment]
Using autogenerated names is no longer an issue in HTML docs, since we display type names unqualified. Do you think it makes sense to always typecheck everything inside psc-publish (then we can leave `Language.PureScript.Docs.Convert.convertDeclaration` alone and not have to match on `ValueDeclaration` values)? Alternatively we could amend `convertDeclaration` to match on `ValueDeclaration` values, and for each one we encounter, add a note; then, go over all of these notes at the end and check whether we already got it via an explicit type declaration, and if not, infer the type and include that?

**Comment by paf31** [comment]
Is this done?

**Comment by hdgarrood** [comment]
No, I didn't get around to trying either of these approaches yet

**Comment by hdgarrood** [comment]
This issue is being tracked in the compiler: #1834
