### ISSUE TITLE
Update to purescript 0.8.5

### ISSUE THREAD

**Issue by tfausak** [purescript/pursuit#210]
> An error occurred, and your package could not be uploaded.
>
> Detailed information:
> At the path: ["modules"][0]["reExports"][0]["declarations"][0]["children"][1]["info"]["type"] 
> Arising from an Aeson FromJSON instance: 
> When parsing Language.PureScript.Types.Type expected an Object with a tag field where the value is one of [TUnknown, TypeVar, TypeWildcard, TypeConstructor, TypeApp, ForAll, ConstrainedType, Skolem, REmpty, RCons, KindedType, PrettyPrintFunction, PrettyPrintObject, PrettyPrintForAll], but got ParensInType. 

[purescript-neon-0.5.0.txt](https://github.com/purescript/pursuit/files/231889/purescript-neon-0.5.0.txt)

**Comment by hdgarrood** [comment]
Ah yes, we had to break the JSON format again in 0.8.5. For now, you'll need to stick to 0.8.4 when uploading. To fix this, we need to do the following (in this order):

* [ ] Update pursuit to depend on purescript 0.8.5
* [ ] Redeploy pursuit:
  * [ ] update the configuration to require packages to use 0.8.5
  * [ ] make a note of all the packages in the database
  * [ ] delete everything in the database (because it will all be using the old format, which Pursuit will no longer be able to cope with)
* [ ] Regenerate all the data (this is fairly easy using https://github.com/hdgarrood/pursuit-check-missing)

**Comment by tfausak** [comment]
Using 0.8.4 to generate documentation is unnecessarily hard since `psc-publish` refuses to work if the Git working tree is dirty.

**Comment by hdgarrood** [comment]
It's not clear to me how these things are related.

**Comment by tfausak** [comment]
In order to build the documentation with PureScript 0.8.4, I need to edit my `package.json` to use the old version. That dirties my working tree.

**Comment by hdgarrood** [comment]
Ah, I see. I'm aware it's a pain; I've detailed the real fix above. Using 0.8.4 is just a temporary workaround.

**Comment by Thimoteus** [comment]
Ahh, so this is going to be similar to what happened a while back with reuploading all the packages?

**Comment by hdgarrood** [comment]
Yeah it is. Maybe I should post on the subreddit again.

**Comment by tfausak** [comment]
Well now I can't upload documentation at all because PureScript 0.8.4 doesn't work with Node 6.0.0.

```
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/taylor/Applications/Homebrew/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! purescript@0.8.4 postinstall: `node --harmony_destructuring lib/install.js`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the purescript@0.8.4 postinstall script 'node --harmony_destructuring lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony_destructuring lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purescript
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/taylor/Documents/Code/purescript-neon/npm-debug.log
```

This is super annoying.

**Comment by hdgarrood** [comment]
Pursuit now accepts uploads from psc-publish 0.8.5. Some packages couldn't be reuploaded, so a few are missing now. I'll follow up with those separately.

**Comment by tfausak** [comment]
Awesome, thank you! I was able to upload [purescript-neon-0.5.2](https://pursuit.purescript.org/packages/purescript-neon/0.5.2) successfully. 

For reference, the issue I had above wasn't actually a problem with PureScript 0.8.4. The same thing happens with 0.8.5. It's a problem with Node 6. See https://github.com/purescript-contrib/node-purescript-bin/issues/19 for the issue itself and https://github.com/purescript/purescript/issues/2075#issuecomment-216060848 for a workaround.

**Comment by tfausak** [comment]
This can be closed as far as I'm concerned. Do you want to keep it open for some reason?

**Comment by hdgarrood** [comment]
No, I actually meant to close it when I last commented. Thanks. :)

**Comment by texastoland** [comment]
Noticed the following and wanted to make sure it's not just an artifact from this issue:

```sh
bash-3.2$ npm info purescript dist-tags
{ latest: '0.9.1', 'node6-0.8.5': '0.8.6-rc.1' }
```

**Comment by hdgarrood** [comment]
I don't think that's related to Pursuit. Also I guess that's probably what we want the dist tags to look like anyway?

**Comment by texastoland** [comment]
Ah picked the wrong issue. I was looking for the one when installing Node 6 broke. I was just making sure we meant to keep the `node6-0.8.5` tag pinned where it is.
