### ISSUE TITLE
Deprecate the web interface for uploading packages?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#212]
Right now, the `pulp publish` and `pulp release` commands are only in prerelease versions, so of course we need to have those in real versions before we can do this, but I would like to deprecate and eventually remove the web upload interface, for the following reasons:

* `pulp` has a much nicer UX. Almost everyone trips up with the `psc-publish > pursuit.json` making the working tree dirty, for instance. Of course this is easy to fix but even so, `pulp` has way fewer steps. It also protects you from making mistakes such as making a tag without realising that your `bower.json` file is not acceptable.
* Implementing the OAuth flow is significantly more complex than using github api tokens, and I think there's a good chance I haven't done it quite right anyway.
* There does not appear to be a good way of gzipping uploads with the web form. I don't want to ask people to pipe the output of `psc-publish` through `gzip`, and nor do I want to distribute a JS implementation of gzip so that the JSON can be gzipped on the client before uploading. Note that gzipping is often necessary for larger packages, eg halogen and batteries.
* Having both upload mechanisms doubles the amount of work in addressing issues like #118.

**Comment by paf31** [comment]
👍
