### ISSUE TITLE
Packages that went missing in the upgrade to 0.8.5

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#213]
Right now, the procedure for upgrading pursuit whenever the JSON format changes is to make a note of everything in the database, delete everything, and regenerate it using the new version of the `psc-publish` (which will then use the new format). Unfortunately, whenever this happens, many packages can't be regenerated and disappear, and the recent upgrade of Pursuit to use PureScript 0.8.5 did end up losing quite a few packages.

This process around the JSON format and upgrades obviously needs rethinking at some point but this is where we are right now. If you're mentioned in this issue, it means that one or more versions of your package is no longer on Pursuit. Sorry about that.

This time, the most common reason by far for packages not successfully reuploading was the `license` field in `bower.json`. As of 0.8.5, we require that it not only exists, but contains a valid SPDX license expression. Here are some examples of SPDX license expressions:

* `MIT`
* `BSD-3-Clause`
* `Apache-2.0`
* `LGPL-3.0+`

I've added a reason after each package for those that failed due to some other reason. If there is no reason listed after your package, it probably means your `license` key in bower.json needs fixing.

In some cases, the latest version of a package is still up, and it's only some older versions which went missing. So it's fine to decide not to do anything if one of your packages is on this list.

I'm happy to answer any additional questions you might have. Also, there's an unsubscribe button on the right hand side if this gets too spammy. :)

The full list of packages which are missing one or more versions:

* @bodil   purescript-eulalie (not on bower)
* @bodil   purescript-signal-socket (not on bower)
* @jutaro  purescript-stsequence
* @DavidHarrison	purescript-functor-compose
* @Fresheyeball	purescript-context
* @Thimoteus	purescript-base64
* @Thimoteus	purescript-hugenums
* @Thimoteus	purescript-simple-parser
* @Thimoteus	purescript-simple-request
* @VerbalExpressions	purescript-verbal-expressions
* @agrafix	purescript-apparch
* @anttih	purescript-rationals
* @brakmic	purescript-fedger
* @brakmic	purescript-ractive
* @brakmic	purescript-redux
* @cdepillabout	purescript-alert
* @cdepillabout	purescript-email-validate
* @cdepillabout	purescript-location
* @cdepillabout	purescript-monad-logger-writer
* @cdepillabout	purescript-monad-supply
* @cdepillabout	purescript-super-spec
* @cdepillabout	purescript-typesafe-localstorage
* @cdepillabout	purescript-words-lines
* @chrisdotcode	purescript-ips
* @clinuxrulz	purescript-stackless
* @clinuxrulz	purescript-stackless-cont
* @dbushenko	purescript-router
* @eskimor	purescript-localstorage
* @ethul	purescript-freeap
* @hdgarrood	purescript-ansi
* @hdgarrood	purescript-benchotron
* @hdgarrood	purescript-eff-functions
* @hdgarrood	purescript-orders
* @hdgarrood	purescript-versions
* @jane	purescript-autocomplete
* @kofno	purescript-wkhtmltopdf
* @mechairoi	purescript-unique
* @null	purescript-in-purescript
* @nullobject	purescript-digraph (some versions failed to compile)
* @paf31	purescript-debugger
* @paf31	purescript-foreign-generic
* @paf31	purescript-foreign-lens
* @paf31	purescript-freet
* @paf31	purescript-leibniz
* @paf31	purescript-nonempty
* @paf31	purescript-signal-loop
* @paf31	purescript-string-parsers
* @paf31	purescript-thermite-aff
* @paf31	purescript-webidl
* @paf31	purescript-yargs
* @passy	purescript-errors
* @passy	purescript-simple-moment
* @purescript	purescript-functors
* @purescript	purescript-parallel
* @purescript	purescript-partial
* @purescript	purescript-validation
* @purescript-contrib	purescript-aff-coroutines
* @purescript-contrib	purescript-form-urlencoded
* @purescript-contrib	purescript-profunctor-lenses
* @purescript-contrib	purescript-strongcheck (Compile error)
* @purescript-contrib	purescript-unsafe-coerce
* @purescript-node	purescript-node-child-process
* @purescript-node	purescript-node-http
* @purescript-node	purescript-node-streams
* @purescript-node	purescript-node-url
* @rightfold	purescript-hash
* @rightfold	purescript-stm
* @sharkdp	purescript-bigints
* @sharkdp	purescript-colors
* @sharkdp	purescript-flare (Unable to resolve dependencies)
* @sharkdp	purescript-flarecheck (Unable to resolve dependencies)
* @slamdata	purescript-ace-halogen
* @slamdata	purescript-affjax
* @slamdata	purescript-halogen
* @slamdata	purescript-pathy
* @slamdata	purescript-uri
* @spicydonuts	purescript-uuid
* @srijs	purescript-indexed
* @tel	purescript-intmaps
* @typed-wire	purescript-typed-wire
* @zudov	purescript-strongcheck-generics
* @zudov	purescript-websocket-simple

**Comment by rightfold** [comment]
Fixed :+1:

**Comment by sharkdp** [comment]
> @sharkdp purescript-bigints
> @sharkdp purescript-colors
> @sharkdp purescript-flare (Unable to resolve dependencies)
> @sharkdp purescript-flarecheck (Unable to resolve dependencies)

Fixed, thanks for the notification :+1:
