### ISSUE TITLE
Packages that need reuploading

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#214]
## Core
* [x] purescript-functors
* [x] purescript-parallel
* [x] purescript-partial
* [x] purescript-validation

## Contrib

* [x] purescript-aff-coroutines
* [ ] purescript-form-urlencoded
* [x] purescript-profunctor-lenses
* [x] purescript-strongcheck (Compile error)
* [x] purescript-unsafe-coerce

## Node
* [x] purescript-node-child-process
* [x] purescript-node-http
* [x] purescript-node-streams
* [x] purescript-node-url

**Comment by hdgarrood** [comment]
cc @paf31 @garyb I'll take care of these.

**Comment by hdgarrood** [comment]
Well, I'll send PRs to the contrib repos that I don't have access to, someone else will have to merge, tag and upload.

**Comment by garyb** [comment]
Thanks for sorting these out!

**Comment by paf31** [comment]
Yes, thanks!
