### ISSUE TITLE
Include date uploaded on package pages

### ISSUE THREAD

**Issue by mpickering** [purescript/pursuit#216]
There is very little meta information on the package pages. It would be good to include some more information. I was looking for the upload date of a package but couldn't find it on the page.

**Comment by hdgarrood** [comment]
👍, but I think I'd rather use the tag date, as the upload date often is a fair bit later than the actual release date of that version. For example, it happens fairly often that a package is released and the author forgets to upload documentation, but someone else uploads documentation a few weeks later.

**Comment by hdgarrood** [comment]
Note to self for later: the required information is present in the JSON in the current compiler `master`. Once the next release after 0.10.5 is out, we can address this.
