### ISSUE TITLE
Take down purescript-typeahead

### ISSUE THREAD

**Issue by mckeankylej** [purescript/pursuit#217]
I just relized that I uploaded purescript-**T**ype**A**head to bower, when people see the package `purescript-typeahead` they will install the wrong bower package as `purescript-typeahead` already exists on bower. I will re-upload it with the same name.

**Comment by hdgarrood** [comment]
Huh, weird, bower's spec says package names may not contain uppercase letters: https://github.com/bower/spec/blob/master/json.md#name

**Comment by mckeankylej** [comment]
werid how is it going to choose between the too? Can you take it down?

**Comment by hdgarrood** [comment]
If you ask bower for purescript-TypeAhead, you'll get your one; otherwise, you'll get the other one; it's case sensitive. I just checked by running `bower info purescript-TypeAhead` and comparing it with `bower info purescript-typeahead`. I can't remove it from pursuit but @paf31 can.

**Comment by paf31** [comment]
Removed, thanks for letting us know.
