### ISSUE TITLE
Links to primitive types are broken

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript/pursuit#218]
The Array link in [Control.MonadPlus](https://pursuit.purescript.org/packages/purescript-control/0.3.2/docs/Control.MonadPlus#t:MonadPlus) links to:

https://pursuit.purescript.org/packages/purescript-prim/0.8.0/docs/Prim#t:Array

Which is broken

**Comment by hdgarrood** [comment]
Thanks for the report.
