### ISSUE TITLE
Almost all searches return no results at the moment

### ISSUE THREAD

**Issue by rgrempel** [purescript/pursuit#221]
At the moment, I'm not getting any results -- as in "No results for ..., sorry." -- for any search, except for searches for package names.

That is, searching for "purescript-lists" works, but searching for "Data.List" does not, and searching for "zip" does not.

**Comment by rgrempel** [comment]
Searches seem to be working again, so I'll close this.

**Comment by oblitum** [comment]
More or less... I've searched for `Maybe` and the results weren't the most useful ones.

**Comment by hdgarrood** [comment]
That is most likely because the newest version of `purescript-maybe` hasn't been uploaded yet.

**Comment by oblitum** [comment]
@hdgarrood ah, ok then, thanks for the info.

**Comment by nicholaskariniemi** [comment]
Is this now working for others? I still don't get any results (other than package names in some specific cases) on https://pursuit.purescript.org/. E.g. "No results for "zip", sorry."

**Comment by hdgarrood** [comment]
Ah, it was working before, but it seems like it's now gone back to how it was when @rgrempel originally reported this. I wonder if this is related to #226...?

**Comment by oblitum** [comment]
I just tried a search for `modifySTRef`, etc and none worked.

**Comment by oblitum** [comment]
ah, my bad.. I guess. I noticed that the search is being whitespace sensitive. Is that desired? I was failing because of an ending whitespace after the function name.

**Comment by oblitum** [comment]
This may be possibly the reason why `:PSCIDEpursuit` is not giving results.
