### ISSUE TITLE
Function search missing

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript/pursuit#222]
If I search for something like `>>=` or `>=>` or `>>>`, nothing comes up, but I can do this in Hoogle.

Maybe this was never implemented, but I thought I remember this working earlier.

**Comment by jplatte** [comment]
This doesn't apply to operators only. The pursuit search search hardly works at all currently (see #221).

**Comment by hdgarrood** [comment]
It did used to work, yes. This is a duplicate of #221.
