### ISSUE TITLE
Invalid json error with pursuit-backups

### ISSUE THREAD

**Issue by foopq** [purescript/pursuit#224]
Hello, I build the latest Pursuit and pointed it to the latest pursuit-backup, but every package I try to navigate to gives me an error like:

11/Jul/2016:11:31:59 -0400 [Error] Invalid JSON in: "/Medias2/PursuitMirror/pursuit/data/verified/purescript-maps/0.5.4.json", error: "Error in $: At the path: [\"modules\"][0][\"declarations\"][0][\"children\"][0][\"info\"][\"dependencies\"][0]\nType mismatch:\nExpected a value of type object\nGot: [[[\"Prelude\"],\"Eq\"],[{\"tag\":\"TypeVar\",\"contents\":\"k\"}]]\n" @(pursu_DMOe3B0gDcwECBz4TiLmlb:Handler.Database src/Handler/Database.hs:89:7)

Is there something I missed in setting up my Pursuit mirror? Thanks!

**Comment by paf31** [comment]
I'm currently using `pursuit-backups` as a backup of the data from the previous version of Pursuit, until more data is migrated to the current version. Until that's done, and I can make another backup, I suggest populating the database manually using `psc-publish`.

I'm interested to hear your experience with maintaining a Pursuit mirror, by the way.

**Comment by paf31** [comment]
I've switched the backups to the new data now.

**Comment by foopq** [comment]
Thank you for the quick response. I should've tried rolling back to the 0.3.10 Pursuit code, which I've now done and it all works (with the same pursuit-backups.. I haven't grabbed the latest yet).
