### ISSUE TITLE
Delete erroneously named package

### ISSUE THREAD

**Issue by garyb** [purescript/pursuit#225]
`purescript-functor-coproducts` was uploaded with a `bower.json` that named it as `purescript-coproducts`, so now it is listed as that, which is incorrect. Can we delete that one? I've also reuploaded with the correct name.

**Comment by paf31** [comment]
Done, thanks.

**Comment by paf31** [comment]
Damn, deleted the wrong one 😄 Could you please reupload the right one?

**Comment by garyb** [comment]
:laughing: Done, thanks!
