### ISSUE TITLE
ERROR: The header content contains invalid characters

### ISSUE THREAD

**Issue by garyb** [purescript/pursuit#229]
I'm receiving this when trying to publish `purescript-zclipboard`@v1.0.1. I've examined the obvious places for strange characters and stuff, and don't seem to have come up with anything. Any ideas what could be the problem?

**Comment by hdgarrood** [comment]
Could be that it doesn't like the format that the program you used to zip it up with uses? How are you creating the file?

**Comment by garyb** [comment]
`pulp publish`

**Comment by garyb** [comment]
Perhaps I should have opened the issue there actually, since that's what is producing this error rather than the API necessarily. I've published many other things succesfully though, which is why I mentioned the library in particular too.

**Comment by garyb** [comment]
This is a `pulp` issue, I just encountered the same thing with `purescript-these`, but managed to upload it with the `psc-publish` json directly instead.
