### ISSUE TITLE
Functions from typeclasses 

### ISSUE THREAD

**Issue by Fresheyeball** [purescript/pursuit#23]
From the Prelude
```purescript
 class Num a where
    (+) :: a -> a -> a
```

When typing `(+)` into pursuit, pursuit shows:
```purescript
(+) :: a -> a -> a
```

I think it really should be showing:
```purescript
(+) :: forall a. (Num a) => a -> a -> a
```

---

Loving all the new work on Pursuit btw

**Comment by joneshf** [comment]
See https://github.com/purescript/pursuit/issues/8
