### ISSUE TITLE
Downgraded?

### ISSUE THREAD

**Issue by garyb** [purescript/pursuit#230]
When trying to upload now I get complaints that pursuit is running 0.8.5 but I generated the data with 0.9.2.

**Comment by LiamGoodacre** [comment]
I saw this too.  I assumed it just hadn't been updated.

**Comment by garyb** [comment]
My uploads using 0.9.x had been working recently, so I think it must have been un-updated somehow.

**Comment by garyb** [comment]
Yeah, it looks like things were reverted actually, as there are a bunch of things missing from the index now.

**Comment by paf31** [comment]
Sorry, operational failure on my part. I forgot to set the older version of the service to not restart on boot.

**Comment by paf31** [comment]
Fixed.
