### ISSUE TITLE
Support other url formats in bower.json

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript/pursuit#249]
Currently psc-publish won't accept other git urls, such as `git+https`:

```
"repository": {
  "type": "git",
  "url": "git+https://github.com/pathto/repo.git"
},
```

**Comment by hdgarrood** [comment]
We have already done some work to allow more than just one format for these URLs (search through the merged PRs on either this repo or the compiler repo for details) so this sounds sensible to me. Unfortunately I don't have a functioning PC at the moment so I won't be able to help with it, though.

**Comment by hdgarrood** [comment]
This is really a compiler issue so I'm going to close it. Also, it seems that `git+https` urls are no longer supported; I can't find any reference to them in https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols and attempting to clone using one is now failing for me:

```
$ git clone git+https://github.com/purescript/pursuit
Cloning into 'multipac'...
fatal: Unable to find remote helper for 'git+https'
```

If this is still something you think we should have could you address these points if/when you open a new issue on the compiler repo, please?
