### ISSUE TITLE
Pursuit is running at ~100% CPU again

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#251]
I'm not sure what's going on this time, but Pursuit seems to run for some time at almost 100% CPU, then gets killed, then starts up again, etc.

Just making a note, this is not urgent at all, but I'd like to come back to this soon.

**Comment by hdgarrood** [comment]
I think one symptom of this might be that most search queries return "no results for X, sorry" at the moment. (Perhaps if the database contains less than some fixed number of entries we should deduce that something has gone wrong and display a different message, like "sorry, the search database is not working at the moment")?

**Comment by paf31** [comment]
This was fixed by the recent Linode upgrade. It was the indexing job which was causing us to run out of memory and restart in a loop.
