### ISSUE TITLE
not easy to find Pursuit through other PureScript resources

### ISSUE THREAD

**Issue by michaelficarra** [purescript/pursuit#27]
I think Pursuit is one of the most valuable resources for PureScript users, yet it is very hard to find any references to it. Let's change that.

- [x] purescript.org
- [x] PureScript by Example book
- [x] PureScript wiki
- [x] PureScript README
- [x] Fix link on [day 23](https://gist.github.com/paf31/8e9177b20ee920480fbc#day-23---pursuit), the one reference I could actually find

**Comment by nwolverson** [comment]
Suggest a link to the website on the front of this repo too

**Comment by hdgarrood** [comment]
I think we can check off purescript.org now, since it's on here: http://www.purescript.org/learn/

**Comment by hdgarrood** [comment]
I just noticed it's in the book now too. That's everything!
