### ISSUE TITLE
Operator aliases do not show up in search results

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#273]
edit: Unless you surround them with parentheses.

**Comment by marcopullo** [comment]
And even that isn't always reliable, e.g. (~>) doesn't find NaturalTransformation.

**Comment by hdgarrood** [comment]
Currently type operators go into the database as e.g. "type (~>)", so you have to search for something like that to allow them to come up. This is obviously not ideal, but it's not immediately clear what to do to address this, so I'm going to make a separate issue.
