### ISSUE TITLE
Include docs for instances?

### ISSUE THREAD

**Issue by chexxor** [purescript/pursuit#275]
The docs for [`Data.Maybe`'s instances](https://github.com/purescript/purescript-maybe/blob/master/src/Data/Maybe.purs#L31) are excellent. Too bad they aren't reflected in [Pursuit's Data.Maybe page](https://pursuit.purescript.org/packages/purescript-maybe/2.0.1/docs/Data.Maybe).

For example, I didn't know I could do `maybe1 <|> maybe2` to get the first Just value encountered until I happened upon those docs in the Data.Maybe source code. It's like the complement of using a do-block to handle Maybe values, which returns Just only if *all* Maybe values are Just.

Should we include these docs in Pursuit?

**Comment by hdgarrood** [comment]
:+1:.There's some discussion on this in #159 too.

**Comment by chexxor** [comment]
Oh, nice. I did a search before creating this but didn't find that thread. Let's close this one, then?
