### ISSUE TITLE
Double-clicking a function name also selects the "Source" text

### ISSUE THREAD

**Issue by wereHamster** [purescript/pursuit#276]
If I double-click a function name in order to copy it, the browser also selects the "Source" text at the right. I have to manually click and drag to select just the function name.

![image](https://cloud.githubusercontent.com/assets/34538/22236617/0c0a52ac-e207-11e6-93d0-b0323b18f391.png)

**Comment by hdgarrood** [comment]
Fixed inside the compiler (rendering HTML happens there now): https://github.com/purescript/purescript/pull/2786
