### ISSUE TITLE
Upgrade to ghc 8.0.2

### ISSUE THREAD

**Issue by craigbilner** [purescript/pursuit#278]
I'm a bit of a Haskell noob and wanted to contribute to this but I can't build it on OSX. I believe this is fixed in 8.0.2 due to some symlinking issues but I'm not entirely sure how to go about upgrading pursuit, would you be able to assist?

**Comment by hdgarrood** [comment]
What's the error you're getting?

**Comment by craigbilner** [comment]
Thanks @hdgarrood, get a load of blow ups on yesod

```
Loading temp shared object failed: dlopen(/var/folders/vr/mhb174x90137tttbcrsbm_500000gn/T/ghc11937_0/libghc_24.dylib, 5): no suitable image found.  Did find:
    	/var/folders/vr/mhb174x90137tttbcrsbm_500000gn/T/ghc11937_0/libghc_24.dylib: malformed mach-o: load commands size (35128) > 32768
```

I think it's related to this [issue](https://github.com/commercialhaskell/stack/issues/2577)

Which suggests it should be fixed but...

If I do

```
stack build --resolver=nightly
```

A lot of the pursuit dependencies blow up

**Comment by hdgarrood** [comment]
Ok - in that case I think upgrading to ghc 8.0.2 is probably the right move. I would recommend deleting stack.yaml and running stack init --resolver=nightly. You might additionally need to modify some version bounds in pursuit.cabal.

**Comment by hdgarrood** [comment]
Let me know if you get stuck - I can have a go at it if you want.

**Comment by craigbilner** [comment]
Thanks @hdgarrood.

Barrier and purescript can't be found so I assume I have to wait until they're upgraded.

**Comment by hdgarrood** [comment]
If it's that barrier and purescript aren't in Stackage snapshots, that shouldn't be a problem; Stack should still be able to deal with that.

**Comment by hdgarrood** [comment]
I'm going to have a stab at this.

**Comment by hdgarrood** [comment]
@craigbilner The easiest way to do it is to use the `compiler` field in `stack.yaml` to override the compiler specified by the snapshot, see my PR. I tried updating to the latest nightly but it will require a few changes in Pursuit's code so I decided to save that for later.
