### ISSUE TITLE
Feature request: library deprecation marking

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/pursuit#287]
The library [purescript-functor-products](https://pursuit.purescript.org/packages/purescript-functor-products/2.0.0) (and others) are deprecated, but this is not displayed anywhere on pursuit.  It may be useful to be able to mark a library as deprecated and have it shown either in a different section on the homepage or with some kind of deprecated label.  Also having search results display that they are from a deprecated library.

**Comment by hdgarrood** [comment]
This does seem like a it would be a good piece of information to have, yeah. In the meantime you can have a deprecation notice appear on Pursuit now by writing it in your README.

**Comment by kevinbarabash** [comment]
Some repos are archived though.  Maybe pursuit could check if the repo is in https://github.com/purescript-deprecated and automatically mark the package as deprecated.

**Comment by hdgarrood** [comment]
I’d prefer not to do that, because that org is only for deprecated core libraries.

**Comment by hdgarrood** [comment]
I think we should probably just not add deprecated libraries to the search index at all.

**Comment by hdgarrood** [comment]
Resolved by #391.
