### ISSUE TITLE
Link to Prim from the front page

### ISSUE THREAD

**Issue by Andrew-Webb** [purescript/pursuit#291]
If I go to Pursuit's front page and do a browser find (ctrl+f) for "prim", there is no match.

If I search (Pursuit search, not browser find) for something that I know exists in the https://pursuit.purescript.org/builtins/docs/Prim page, then I don't get results from `module Prim`.

E.g. if I search for "Record", I get results only for modules `Data.Either.Compact` and `Data.RateLimit`.

As a result, I keep https://pursuit.purescript.org/builtins/docs/Prim bookmarked separately from Pursuit, since it's such a useful page.  But it would be nice if it was reachable by the normal Pursuit user interface.

**Comment by hdgarrood** [comment]
We have an issue for the search results already: #265. I'm not sure about the front page; the front page is a list of packages, and Prim is a module which is built in to the compiler so it doesn't exist in any package, and so it's not immediately clear how to include it. I'll think about it though.

**Comment by Andrew-Webb** [comment]
> Prim is a module which is built in to the compiler so it doesn't exist in any package, and so it's not immediately clear how to include it

https://github.com/hdgarrood/purescript-prim refers to `purescript-prim` as a pseudo-package, so maybe it could be listed on the front page between `purescript-prelude` and `purescript-prng`.  Kinda nice that it would be situated so closely to the prelude.

**Comment by hdgarrood** [comment]
I should take that down, it's not used any more.

**Comment by hdgarrood** [comment]
Fixed by #331.
