### ISSUE TITLE
compareTypes algorithm should order typevar results by descending generality

### ISSUE THREAD

**Issue by matthewleon** [purescript/pursuit#293]
Sorry for the wording of the title. I hope that my example below will make clear what I mean.

This follows up on PR #286.

Basically, I think that when searching using type variables, results should be ordered by decreasing "degree of polymorphism."

Example: The front page links to a search for "(a -> b) -> f a -> f b"

Current result order:

1. `censor :: forall w m a. MonadWriter w m => (w -> w) -> m a -> m a`
2. `liftA1 :: forall f a b. Applicative f => (a -> b) -> f a -> f b`
3. `liftM1 :: forall m a b. Monad m => (a -> b) -> m a -> m b`
4. `seeks :: forall s a w. ComonadStore s w => (s -> s) -> w a -> w a`
5. `squigglyMap :: forall f a b. Functor f => (a -> b) -> f a -> f b`

Desired result order (pretend that the five results above are the _only_ ones):

1. `squigglyMap :: forall f a b. Functor f => (a -> b) -> f a -> f b`
2. `liftA1 :: forall f a b. Applicative f => (a -> b) -> f a -> f b`
3. `liftM1 :: forall m a b. Monad m => (a -> b) -> m a -> m b`
4. `seeks :: forall s a w. ComonadStore s w => (s -> s) -> w a -> w a`
5. `censor :: forall w m a. MonadWriter w m => (w -> w) -> m a -> m a`

Reasoning here: The functions that unify type variables `a` and `b` follow the ones where `a` and `b` are separate. `Functor => Applicative => Monad`. As for `ComonadStore` and `MonadWriter`, that's trickier (ideas? could go with depth of position in a tree of classes, but there's probably something better).

This is the _opposite_ behavior from the one we employ with concrete types. I think this makes sense. When the user searches for a type signature with both concrete types and type variables, it seems to me that the user wants the concrete type matched as closely as possible, and the variable to be as unconstrained as possible. This should produce the most relevant ordering (based on types alone).

**Comment by hdgarrood** [comment]
Sounds sensible to me, although it's a little hard to say without having seen an implementation.

**Comment by hdgarrood** [comment]
See #355.
