### ISSUE TITLE
don't publish documentation link

### ISSUE THREAD

**Issue by matthewleon** [purescript/pursuit#297]
It can be a bit confusing for users that Pursuit republishes the full README, including the (recursive) link to the documentation on Pursuit. I have often found myself absent-mindedly clicking this link, probably out of some instinctive desire to "get to the docs", not knowing that I'm already on them.

I'm not really sure if there would be some elegant way of censoring this part of the README. A simple, though a bit ugly, solution, would be to just give the "Documentation" heading some special significance, perhaps searching for any paragraph under that heading that links to the same package in Pursuit, and eliminating that paragraph, or the whole "Documentation" section if it's the only one.

**Comment by hdgarrood** [comment]
There's discussion of this issue a bit further down in https://github.com/purescript/pursuit/issues/150, in fact I think this issue is probably a duplicate of that one.

**Comment by matthewleon** [comment]
Thanks.
