### ISSUE TITLE
change package name

### ISSUE THREAD

**Issue by coot** [purescript/pursuit#299]
I change a name of [purescript-recompose](https://pursuit.purescript.org/packages/purescript-recompose/0.0.1) to [purescript-react-hocs](https://pursuit.purescript.org/packages/purescript-react-hocs/0.2.0)
Sine there is a [purescript-recompose](https://github.com/ecliptic/purescript-recompose) project that made `recompose` bindings for React, which might want to be on pursuit one day.  Is there a way to remove my old `purescript-recompose` docs from pursuite.  `purescript-react-hocs` still makes sense since I don't follow `recompose` and I want to stay more close to purescript.

**Comment by paf31** [comment]
I've deleted `purescript-recompose` from Pursuit, thanks.

**Comment by coot** [comment]
Thanks.
