### ISSUE TITLE
Source links don't work on functions from re-exported modules from other packages

### ISSUE THREAD

**Issue by rightfold** [purescript/pursuit#304]

**Comment by hdgarrood** [comment]
Can you give an example please?

**Comment by rightfold** [comment]
Sorry, I totally forgot. For example: https://pursuit.purescript.org/packages/purescript-stuff/1.1.0/docs/Stuff#t:Alt. Clicking the source link will give a 404.

**Comment by hdgarrood** [comment]
Ah, I see. Thanks for the report :)
