### ISSUE TITLE
don't limit search results

### ISSUE THREAD

**Issue by cdepillabout** [purescript/pursuit#305]
It appears that Pursuit limits search results to a fixed number.

For instance, when I search for ["encode"](https://pursuit.purescript.org/search?q=encode), it doesn't return the result `encodeURIComponent`.  It does, however, return this result when I search for something more specific like ["encodeuri"](https://pursuit.purescript.org/search?q=encodeuri).

It would be nice to use paging to return _all_ results.

Or, at the very least, it would be nice to add a little message to the bottom of the search results page saying that there may be more results that aren't shown.

**Comment by hdgarrood** [comment]
:+1: I'd like to investigate paging results.
