### ISSUE TITLE
How the deprecation of bower would affect pursuit?

### ISSUE THREAD

**Issue by notgiorgi** [purescript/pursuit#306]
As you can see [here](https://github.com/bower/bower/issues/2298), bower is getting deprecated. How would this affect pursuit?

Edit: fixed the link

**Comment by hdgarrood** [comment]
That link is a 404 for me. I had a look around and wasn't able to find any indication that bower has been deprecated. Could you point to the specific comment that you saw that says bower is deprecated please?

**Comment by notgiorgi** [comment]
I fixed the link.

Also take a look at the website: https://bower.io

**Comment by hdgarrood** [comment]
Ok, thanks. Looking at the very last comment:

>  Please keep in mind that even I don't have much free time, I'll maintain and keep Bower alive, so all current projects that use Bower, will continue to work.

Given this, I'm not sure we need to worry about this in the short term. In the long term I think the whole PureScript ecosystem, not just Pursuit, will want to move away from Bower. [psc-package](https://github.com/purescript/psc-package) is a part of that, for instance. However it's a bit early to say exactly how that will look.
