### ISSUE TITLE
Two Foreign examples give 404 on Pursuit

### ISSUE THREAD

**Issue by gspia** [purescript/pursuit#307]
The example section of Foreign package on [Pursuit](https://pursuit.purescript.org/packages/purescript-foreign/4.0.0) has old (?) links:

Simple Types link refers to JSONSimpleTypes.purs and Arrays link refers to JSONArrays.purs.

The example dir has SimpleTypes.purs and Arrays.purs.

(This issue is moved from a list of issues at purescript/purescript-foreign, issue number 64 there. Hmm, how to link to the issues of other packages? Late add: thank you hdgarrood, here is the link  purescript/purescript-foreign#64 even though it is below also :) )

**Comment by hdgarrood** [comment]
Like this: purescript/purescript-foreign#64 :smile:

**Comment by hdgarrood** [comment]
I think Pursuit is behaving correctly here. It pulls in the version of the readme from the corresponding tag in the repo, so here v4.0.0. Looking at the purescript-foreign readme at the v4.0.0 tag it does indeed point to a nonexistent page: https://raw.githubusercontent.com/purescript/purescript-foreign/v4.0.0/README.md so I guess the readme must have been updated after v4.0.0 was tagged. I think the best thing to do here is to release a v4.0.1 with the updated readme.
