### ISSUE TITLE
latest package releases not reflected on site

### ISSUE THREAD

**Issue by matthewleon** [purescript/pursuit#308]
example: https://pursuit.purescript.org/packages/purescript-foldable-traversable/3.0.0

3.1.0 3.2.0 and 3.3.0 are nowhere to be found.

**Comment by hdgarrood** [comment]
This is not a pursuit issue, it seems that those versions of those packages have simply not been uploaded.

**Comment by hdgarrood** [comment]
I've just uploaded those versions to Pursuit.
