### ISSUE TITLE
Request package removal?

### ISSUE THREAD

**Issue by LightAndLight** [purescript/pursuit#314]
How can I request the removal of my package?

I published `purescript-records` to Pursuit only to realise someone else has a package of the same name on Bower. I'll rename my package or make sure there are docs for the one on Bower. Either way, I need to have `purescript-records` taken off Pursuit.

Thanks

**Comment by paf31** [comment]
Done, thanks for the report.

**Comment by LightAndLight** [comment]
Thanks Phil.
