### ISSUE TITLE
Order by core libs first in search results

### ISSUE THREAD

**Issue by Thimoteus** [purescript/pursuit#327]
Mentioned [here](https://github.com/purescript/pursuit/issues/326#issuecomment-324371305) it'd be nice if names from core libs were displayed at the top, for example [searching for apply](https://pursuit.purescript.org/search?q=apply), the definition of `<*>` isn't shown until the fourth listing.

**Comment by hdgarrood** [comment]
Perhaps it would be better to use number of reverse dependencies (see also #292); that should achieve what's wanted here but also be useful for results outside of the core libraries.
