### ISSUE TITLE
purescript-precise package not found

### ISSUE THREAD

**Issue by paulyoung** [purescript/pursuit#334]
I was unable to find anything at https://pursuit.purescript.org/packages/purescript-precise for https://github.com/purescript-contrib/purescript-precise even though I was able to install it.

**Comment by paf31** [comment]
Someone just needs to explicitly upload it. You don't need to be the owner to upload it though.

**Comment by paulyoung** [comment]
@phil would you mind explaining how I was able to download it if it wasn't already uploaded?

**Comment by paulyoung** [comment]
Same question for other packages too.

"Module documentation is published on Pursuit." in all the READMEs is a bit misleading 😃

**Comment by paf31** [comment]
I assume you meant you downloaded it from Bower/GitHub? The two aren't connected - Pursuit uploads are completely separate.

**Comment by paulyoung** [comment]
Of course :man_facepalming:

**Comment by hdgarrood** [comment]
> Of course :man_facepalming:

Forgive me if I'm misinterpreting but what I take from your comment is that the way packages and docs are currently hosted in separate places is obviously wrong and should never have been done that way. I will freely admit it's not ideal but we had to make a tradeoff based on what was actually achievable based on the resources we have. Your comment doesn't seem either helpful or nice.

The error message you saw also admittedly isn't great. It has been improved in master, but I think with a small amount of effort we can probably make it clearer still. I don't have time for that but maybe someone else will.

A good rule of thumb is that if a package claims to be on pursuit but isn't, in almost all cases, that's something the package maintainer needs to address, not a pursuit issue.

**Comment by paulyoung** [comment]
My comment was referring to the fact that I'd forgotten that packages obviously aren't hosted on Pursuit – I'd even typed `bower install purescript-precise`. Sorry that it was ambiguous.

**Comment by hdgarrood** [comment]
Oh, I’m so sorry! I didn’t see that it could be read that way at first.

**Comment by paulyoung** [comment]
It's all good 😄
