### ISSUE TITLE
Change Help link at pursuit.purescript.org to point to user help

### ISSUE THREAD

**Issue by marick** [purescript/pursuit#339]
The banner at Pursuit has a Help link:

<img width="869" alt="32580068-3ee863dc-c4a9-11e7-89d5-7e90143c8c72" src="https://user-images.githubusercontent.com/71909/33177764-7154260e-d029-11e7-857d-0cab23ed9c1d.png">

It goes to help for package maintainers. I suggest it go to help for Pursuit users, so that they know, for example, that you should search for Data.String rather than String.

I would be very happy to write that help page, if paired with someone who knows how Pursuit works.

The "Publish" sidebar text and link are good and, I think, sufficient.

**Comment by hdgarrood** [comment]
It sounds to me like the page you're looking for is the one described in #326. Is there anything you think needs writing which wouldn't be covered by that?

**Comment by marick** [comment]
No. People still need to know how to use the search effectively, and know how to understand what's on the page they see as a result of a search. I don't think people not coming from hoogle have the background to intuit those things.

**Comment by hdgarrood** [comment]
Ok; how about this? https://gist.github.com/hdgarrood/ad6eb9f92b97d989c3e52b0eccf800bb

**Comment by marick** [comment]
As an old magazine editor, I have some changes. Should I edit your markdown, or would you prefer something different?

**Comment by marick** [comment]
(The main focus would be on what kind of things people are looking for, vs. what kind of things they get.)

**Comment by hdgarrood** [comment]
Sure, go ahead.

**Comment by hdgarrood** [comment]
I'm closing this for now as I've added what I wrote above to the help pages, but please open new issues if/when you have further suggestions.

**Comment by marick** [comment]
Will do. It's on my TODO list, nearing the top.
