### ISSUE TITLE
Sort by Update Date

### ISSUE THREAD

**Issue by born2defy** [purescript/pursuit#340]
It would be great to be able to sort the packages on Pursuit by their most recent update date.  This way we can easily see which packages are the most actively maintained without having to view each package individually.

**Comment by hdgarrood** [comment]
I'm not really aware of any situation where it's useful to ask 'which packages are the most actively maintained', as opposed to 'which packages are the most actively maintained *for x specific task*'. Given that it's unlikely that more than 2 or 3 packages will exist for any given task, it's not too much effort to just look at each of them individually, I don't think.

**Comment by born2defy** [comment]
I suppose you could look at it that way, but pursuit already publishes a short list of recently updated packages which caused me to think it wouldn’t be too much effort to turn that into a filter.  I agree it’s not a critical feature though.

**Comment by hdgarrood** [comment]
I'm sure it wouldn't be too much effort, but that doesn't necessarily mean it's worth implementing; there's a maintenance cost to the code and also a cost to the UI in that it would become more complex. I'm going to close this for now but maybe we can revisit this later.
