### ISSUE TITLE
Different example searches?

### ISSUE THREAD

**Issue by natefaubion** [purescript/pursuit#342]
I know the examples are pretty simple, but they aren't very helpful. Searching for `map` brings up `Data.Functor.map` as the 16th or so result, and the search for it's signature doesn't bring up `map` _at all_. Using module names works pretty well though.

**Comment by hdgarrood** [comment]
Yes, it's definitely not ideal. I'm going to work a bit over the next few days on fixing some of these issues with the search; I'll revisit this afterwards.

**Comment by hdgarrood** [comment]
I think, after having merged #353 and #351, we can close this.
