### ISSUE TITLE
Reimplement as a server-side app

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#36]
/cc @hdgarrood 

I would like to integrate Pursuit with `psc-pages`, and I think that this would be a good time to think about restructuring the app as a purely server-side app written in Haskell.

Right now, getting the entire app running is a little tricky, but I think we can simplify it. I would like to get to the point where one person can get the app running by simply `cabal run`ning it, and then hopefully increase the rate of development.

My proposal:

- The entire app runs in-memory on the server.
- The database is contained in a `TVar`, and refreshed periodically using the existing `generator` code.
- `data.json` is not needed any more.
- The `psc-pages` code runs server-side to generate module documentation on the fly (may need some slight modification)
- Search is implemented in memory, and links to module documentation.
- The database structure is changed to accommodate packages, package search, etc.

Any thoughts?

**Comment by hdgarrood** [comment]
So is the main motivation for this to simplify the architecture? I can certainly get behind that.

Could you go into a little bit more detail about the new database structure?

**Comment by paf31** [comment]
Well, we could use something like Postgres, and I'm happy to set that up on the community server, but it's another headache from a dev standpoint when the data is so small.

So I suggest we put things in memory, and have the following "tables" (probably `Map`s and sorted lists, `Data.Trie` is probably overkill):

- Package
- Module (in a package)
- Declaration (in a module)

**Comment by hdgarrood** [comment]
Cool, sounds good to me. What about the UI? Do we just have a single search box that you type stuff in and it can give you back either packages, modules, or declarations as resuts?

**Comment by paf31** [comment]
I was thinking of breaking it up into

- Package list
- Package page for each package (with a list of modules)
- Doc page for each module
- Search page

**Comment by hdgarrood** [comment]
:+1: 

Were you thinking of using Scotty? Also do you want to start this off, or shall I?

**Comment by paf31** [comment]
Probably Scotty and `blaze-html`, just to keep things simple. I can put together a repo with the basics this evening if you like.

**Comment by hdgarrood** [comment]
Yep, sounds good!
