### ISSUE TITLE
Display variable names in addition to type signature

### ISSUE THREAD

**Issue by adius** [purescript/pursuit#363]
e.g.

Not very helpful:

```purescript
getPerson :: String -> String -> String -> String -> Person
```

Much better:

```purescript
getPerson :: String -> String -> String -> String -> Person
getPerson firstname lastname nickname note =
```

**Comment by hdgarrood** [comment]
This is somewhat complicated by the fact that not necessarily every argument will be named, i.e. when writing in point-free style:

```purescript
getPerson :: String -> String -> String -> String -> Person
getPerson = getFromTable "People"
```

and when using different kinds of patterns and/or multiple alternatives:

```purescript
f (Just true) = 2
f (Just false) = 1
f Nothing = 0
```

or

```purescript
maybe _ f (Just x) = f x
maybe default _ Nothing = default
```

I don't want people to find themselves in a situation where they want to do some refactoring which has no consequence for any users of a library, but they're unable to do so without (possibly accidentally) removing information from the docs, or making the docs more confusing. For example, you could argue that we could mechanically extract the names `default` and `f` for at least the first two arguments of `maybe` above, but I think it's probably better to just let the library author write docs which include named arguments, like

> The function `maybe default f`, when given a `Just` value, applies `f` to it. When given `Nothing`, the `default` value is returned.

**Comment by nwolverson** [comment]
[Idris has a nice answer to this](http://docs.idris-lang.org/en/latest/reference/syntax-guide.html#named).

(Arguably the above example is a problem of stringly typed functions, e.g. the string match functions were bad for this also before the use of `Pattern` newtypes)

**Comment by adius** [comment]
Mh, thanks for feedback - good point!
Maybe we could add some comment keyword to include the argument names?
It would really be a shame to waste the precious meta information it contains when it's available.

For example:

```purescript
-- | Smart constructor for a Person
-- | @showArgumentNames
getPerson :: String -> String -> String -> String -> Person
getPerson firstname lastname nickname note =
```

**Comment by adius** [comment]
@nwolverson Thanks for the info. The named params looks cool `(first : String) -> ...`.
But all the useless duplication of variables is really a fail
```idris
||| @first The person's first name
makeHello : (first : String) -> ...
makeHello first last = ...
```
3 x `first` and 2 x `makeHello`. So much to DRY. 🙈

**Comment by adius** [comment]
I keep thinking that the actual problem are `type`s.
They should have been designed something like this:
```haskell
type $FirstName = String
data Note = Note Language $Body
…
getPerson :: $FirstName -> $LastName -> $NickName -> Note -> Person
```

So that one would immediately be able to differentiate type aliases and real types.

**Comment by adius** [comment]
Oh, I got another Idea!
Couldn't we check if any of the arguments are type aliases, and if so display the alias type as well?

```purescript
getPerson :: FirstName -> LastName -> NickName -> Note -> Person
                String      String      String
```

Then we could just use type aliases all the time and be done :grin:
What do you think @hdgarrood ?

**Comment by hdgarrood** [comment]
That style is generally considered to be an anti-pattern, and adding a feature like that would arguably encourage it, which I’d rather not do.

**Comment by adius** [comment]
Mh ... I understand it's an antipattern because type aliases and real types can't be differentiated, right? The dollar proposal would fix that, but I guess it's out of scope to fundamentally change the Syntax 😉.

The PureScript community could also establish a best practice to include the actual type in type aliases. E.g. `FirstNameString -> LastNameString -> ...`.

It's shorter than idris` `(firstName : String) ->  (lastName : String) -> …` and could be implemented with the existing infrastructure.

Or as alternative what do you think of `-- | @showArgumentNames`

**Comment by adius** [comment]
Or maybe just a docstring right above:

```purescript
-- | @signature FirstName -> LastName -> NickName -> _ -> _
getPerson :: String -> String -> String -> Note -> Person
```

**Comment by hdgarrood** [comment]
I’m not keen on either of `@showArgumentNames` or `@signature` because it’s a nontrivial implementation effort and it’s likely to be better in general anyway for the author to just document their code properly.

**Comment by hdgarrood** [comment]
Re type synonyms, there are plenty of cases where they are useful and where it would not really be helpful to distinguish them from real types, so I wouldn’t agree that that is the problem there. For example, `type Reader r = ReaderT r Identity`, or `type MyAppM = ReaderT Config (StateT State Aff)`, or the stuff inside any lens library. You might want to later convert `MyAppM` to a `newtype` but it would be a pain to have to remove sigils everywhere it was used. I’ve also had a case where a library I wrote defined a `Parse` monad which was later generalised to a `ParseT` monad transformer; by defining `Parse` as a type synonym of `ParseT` with the inner monad fixed as `Identity` it was possible to make this a non breaking change without introducing a load of duplicated code.

The problem with type synonyms of the form `type FirstName = String` is that they suggest something more structured or type safe than just `String`, ie that they are misleading. When type synonyms are used well this isn’t really an issue.

**Comment by adius** [comment]
Thanks for the clarification! Makes sense that single element type synonyms are the problem …

>  it’s likely to be better in general anyway for the author to just document their code properly

First problem: What means properly? 

```purescript
-- | This is a function which … <lots of lots of unhelpful prose>
getPerson :: String -> String -> String -> Note -> Person
```

This can be really unreadable and feels like much more effort than just adding a line

```purescript
-- | :: FirstName -> LastName -> NickName -> _ -> _
```

So I guess many developers will just add no documentation at all and think: "Well the signature should be enough". Point in case: https://pursuit.purescript.org/packages/purescript-maps/3.5.0/docs/Data.Map
Most functions would be easily understandable if there was an extra line with the semantic meaning without much extra documentation necessary, but so it's just a pain in the ass.

```purescript
alter :: forall k v. Ord k => (Maybe v -> Maybe v) -> k -> Map k v -> Map k v
```

vs.

```purescript
alter :: AlterFunction -> Key -> InputMap -> AlteredMap
```

**Comment by hdgarrood** [comment]
"properly" obviously can't be precisely defined here; that's a question for library authors to grapple with.

> Most functions would be easily understandable if there was an extra line with the semantic meaning without much extra documentation necessary

What you're now suggesting is a convention for documenting code, which is outside the scope of this issue tracker, really. I'm going to close this for now as I don't think I want to implement the suggestions made here.

**Comment by adius** [comment]
> What you're now suggesting is a convention for documenting code

You're right and that was not my intention.

I just really bugs me, that there is great documentation (the variable names), but we don't show it.

I think it would be really cool to also show the variable names (if they exist).
This shouldn't be to hard to implement, right?

> want to do some refactoring which has no consequence for any users of a library, but they're unable to do so without (possibly accidentally) removing information from the docs

They can simply extend the normal documentation, like you think they should do anyways.
So nothing lost, but it would help a lot for all the packages out there with no documentation but helpful variable names.

What do you think?

**Comment by hdgarrood** [comment]
You’re right that it probably wouldn’t be particularly difficult, but I’d still rather not do it, for reasons I’ve explained earlier in this thread.

I think it’s also worth noting that you can already very easily check the source by following the “source” link, whenever you find yourself in a situation where this information would be useful.

**Comment by adius** [comment]
😞

**Comment by chexxor** [comment]
I agree with @hdgarrood on this one, if pursuit has this feature, it's effectively encouraging people to write poorly-typed functions in their libs. I'd rather send a PR to those few libs which have poor type signatures than change pursuit.

Where is this a real problem right now? Can you link? I haven't seen this problem before.

**Comment by adius** [comment]
It's encouraging people to use understandable variable names, because they will be shown in the documentation. Instead of using cryptic one letter variables they only can understand themselves and then trying to fix it up with documentation. It they add it at all.

E.g. this snippet from Graphics.Drawing

```purescript
-- | Create a rectangle from the left, top, width and height parameters.
rectangle :: Number -> Number -> Number -> Number -> Shape
rectangle x y w h = Rectangle { x, y, w, h }
```

could have been written liken

```purescript
rectangle :: Number -> Number -> Number -> Number -> Shape
rectangle topLeftX topLeftY width height =
  Rectangle { x: topLeftX, y: topLeftY, width, height }
```

And if pursuit would show the argument line he wouldn't have to write that useless comment which is actually even a little misleading as it sounds like the for paramerters would be `left top width height` which makes no sense.
Also it would be better readable because the parameter names would be in a consistent format and better rendered than some continuous comment text.
And it removes the danger of changing the code and forgetting to update the documentation, because the code is the documentation.

**Comment by adius** [comment]
Actually it should have been implemented like this:

```purescript
rectangle :: Point -> Number -> Number -> Shape
rectangle topLeft width height =
  Rectangle { topLeft, width, height }
```
But that's another topic ...

**Comment by chexxor** [comment]
That's a good example, but this automatic type var showing in pursuit should only happen for confusingly typed functions, because I don't want to see the arg names for *every* function in pursuit. This sounds tricky to implement. 

I understand the problem, but the solution you chose isn't one that universally improves pursuit's function description. I prefer pursuit treating all functions equally. Docs for the function seem like a much simpler solution to the problem you state. If the docs are wrong, just make a PR to clarify, or an issue to ask for help to clarify.

**Comment by adius** [comment]
Mh, I guess you have a point. So maybe how about this - completely opt in:

![functions](https://user-images.githubusercontent.com/969983/34918227-637a32ac-f947-11e7-818d-ffbfea4bb192.jpg)

**Comment by hdgarrood** [comment]
That's what the "Source" link is for. I'd like to host source code on Pursuit eventually though; see #137.

**Comment by adius** [comment]
Well, this would actually be pretty cool :grin:
