### ISSUE TITLE
Incorrect types displayed for constructors with 2 or more arguments

### ISSUE THREAD

**Issue by jonathanlking** [purescript/pursuit#373]
The type displayed for the `Tuple` constructor is incorrect, with `Tuple :: forall b a. (a -> b) -> Tuple a b`  displayed instead of `forall b a. a -> b -> Tuple a b`. Additionally a search for `a -> b -> Tuple a b` doesn’t give any (useful) results, but `(a -> b) -> Tuple a b` does.

As noted by @hdgarrood (on the purescript-begginers slack channel) there appears to be an issue with data constructors with 2 or more arguments - other examples are:

  * `Pair :: forall a. (a -> a) -> Pair a`
  * `CofreeF :: forall b f a. (a -> (Unit -> (f b))) -> CofreeF f a b`

**Comment by jonathanlking** [comment]
I had a quick look and `typeToText` in [`searchIndex.hs`](https://github.com/purescript/pursuit/blob/0d0e39e9b7ab688dd82b8514e63687528e1eb532/src/SearchIndex.hs#L240) appears responsible for generating the (incorrect) type. This in turn uses `renderType` from [`Language.PureScript.Docs`](https://github.com/purescript/purescript/blob/38f631c71367cffcc973ce0dab2229e81969e161/src/Language/PureScript/Docs/RenderedCode/RenderType.hs#L176) in the Purescript repo, which is where I suspect the problem may actually lie.

**Comment by hdgarrood** [comment]
I’m fairly sure that renderType is correct, because the types of things do show up correctly in the actual docs - it’s just search results which are wrong here, I think. My suspicion is that the problem is in extractChildDeclarationType in SearchIndex.hs.

**Comment by jonathanlking** [comment]
Thanks for the pointer - I've updated `extractChildDeclarationType` (sorry about the multiple commit messages, I didn't realise force pushing did this).
