### ISSUE TITLE
Visually separate the footer from the results

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#38]
At the moment it looks a bit like the "Source" link will take you to the source for the last result on the page.

**Comment by paf31** [comment]
I think we should get rid of Source, and move the PureScript link into the header, making the current header into a Bootstrap `navbar` with an inline search form. Then when we add new pages, we will have a place to put them all. What do you think?

**Comment by hdgarrood** [comment]
sounds good :+1:
