### ISSUE TITLE
errorcontrol links to Prelude instead of source

### ISSUE THREAD

**Issue by texastoland** [purescript/pursuit#381]
I was reading the docs for [purescript-errorcontrol](https://pursuit.purescript.org/packages/purescript-errorcontrol/0.2.1/docs/Error.Control) but the docs link inside [Prelude](https://github.com/purescript/purescript-prelude/blob/v0.2.1/src/ErrorControl.purs) instead of @LukaJCB's [repo](https://github.com/LukaJCB/purescript-errorcontrol/blob/master/src/ErrorControl.purs).

**Comment by hdgarrood** [comment]
This is because the repo url in bower.json is incorrect. Unfortunately there’s no way to fix this with existing versions but the author can fix this by uploading a new patch release.

**Comment by texastoland** [comment]
Looks like @safareli fixed it in LukaJCB/purescript-errorcontrol@95e0488 and just needs uploaded thanks!
