### ISSUE TITLE
Module Control.Monad.Eff.Console was not found.

### ISSUE THREAD

**Issue by samiulla123** [purescript/pursuit#383]
I tries to run pulp run or pulp build it showing error as.
* Building project in /home/ubuntu/my-project
Error found:
in module Main
at src/Main.purs line 3, column 1 - line 3, column 33

  Module Control.Monad.Eff.Console was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
or to contribute content related to this error.

* ERROR: Subcommand terminated with exit code 1

**Comment by LiamGoodacre** [comment]
@samiulla123: looks like your version of pulp is old.  Make sure `pulp` and `purescript` are up to date.

**Comment by hdgarrood** [comment]
I think @LiamGoodacre is right, yes. For future reference, [Slack](https://functionalprogramming.slack.com) or [Discourse](https://discourse.purescript.org) are more appropriate places for this kind of question.
