### ISSUE TITLE
Accidentally uploaded a package with a wrong name.

### ISSUE THREAD

**Issue by alexknvl** [purescript/pursuit#392]
https://pursuit.purescript.org/packages/purescript/0.2.0
https://pursuit.purescript.org/packages/purescript-stablename/0.3.0

Could you please take that first one down?
Sorry for the inconvenience.

**Comment by hdgarrood** [comment]
@paf31: ^

@alexknvl: you may want to unregister the package on the Bower registry too, with `bower unregister`.

**Comment by alexknvl** [comment]
@hdgarrood Done.

**Comment by hdgarrood** [comment]
Thanks, and thanks for letting us know!
