### ISSUE TITLE
Website has degraded

### ISSUE THREAD

**Issue by chekoopa** [purescript/pursuit#394]
Now it feels dizzy, throwing 502 and 504's, the search doesn't work at all.
I still can navigate straight to docpages, but README is being lost at some loads (refresh does help, excluding same 5xx answers).

What's going on?

An extra point for self-hosting/offline capability.

**Comment by seanyu4296** [comment]
i can confirm this is happening

**Comment by JordanMartinez** [comment]
People on the Slack channel says the issue has to do with Cloudflare. Phil
is also the only one who has the necessary access to fix this, I believe.
You can set up a local instance of Pursuit, but I'm not sure how to do
that.

**Comment by hdgarrood** [comment]
This has been fixed now, as far as I’m aware.
