### ISSUE TITLE
Pursuit doesn't support current JSON schema for kind annotations in 'forall' contexts

### ISSUE THREAD

**Issue by matthew-hilty** [purescript/pursuit#398]
I've gotten the error message shown below after trying to publish a new version of a package.

It looks like Pursuit's version of the PureScript compiler (specifically, its `typeFromJSON` function) doesn't care for kind annotations in 'forall' contexts so much.

@hdgarrood mentions in #397 that the maintainers are planning on updating Pursuit against the latest compiler. This perhaps may be another reason for a new build.

```
* Uploading documentation to Pursuit...
* At the path: ["modules"][0]["reExports"][0]["declarations"][0]["children"][0]["info"]["type"]
Arising from an Aeson FromJSON instance:
cannot unpack array of length 4 into a tuple of length 3
Usually, this occurs because the JSON data was generated with a newer version of the compiler than what Pursuit is currently using, and the JSON format changed between compiler releases.
This data was generated with 0.13.2 of the compiler.
Pursuit is currently using 0.12.2.
You might be able to fix this by temporarily downgrading to 0.12.2 to generate the JSON data.

* ERROR: Expected an HTTP 201 response from Pursuit, got: 400
error Command failed with exit code 1.
```

**Comment by hdgarrood** [comment]
@matthew-hilty Pursuit has now been updated so this should work, can you try again please?

**Comment by hdgarrood** [comment]
I'm going to assume this is fixed; please let me know if it isn't.
