### ISSUE TITLE
Delete package

### ISSUE THREAD

**Issue by mwalkerwells** [purescript/pursuit#403]
Accidentally published a package under "purescript-purescript-typelevel-rowlist-limits".
https://pursuit.purescript.org/packages/purescript-purescript-typelevel-rowlist-limits/0.0.2

The correct package is "purescript-typelevel-rowlist-limits".
https://pursuit.purescript.org/packages/purescript-typelevel-rowlist-limits/0.0.3

Would it be possible to delete the first one?

**Comment by hdgarrood** [comment]
Yep, done!
