### ISSUE TITLE
Link to README in case it can't be show due to rate limiting

### ISSUE THREAD

**Issue by andys8** [purescript/pursuit#417]
Currently if there is the README can't be fetched due to rate limiting, pursuit is showing:

![image](https://user-images.githubusercontent.com/13085980/92021499-2a418d00-ed5a-11ea-87f2-5fa0ab64d26b.png)

https://github.com/purescript/pursuit/blob/d995a0411c65aa4506074f10acc95188f550502b/src/TemplateHelpers.hs#L125-L129

## Possible improvement

We could add a hint ("Click here to open README instead") and additionally link to 
`https://<REPO>/blob/master/README.md`

**Comment by hdgarrood** [comment]
I would actually prefer to stop using the GitHub API for readme tendering entirely; see #150 and https://github.com/purescript/purescript/issues/3917

**Comment by andys8** [comment]
In that case the issue would be superseeded. 

#150 is 5 years old. Is this issue a small improvement one could do anyway? Otherwise I'm gonna close it :)

**Comment by hdgarrood** [comment]
Yeah, we could do this instead anyway. Using "click here" as link text is generally best avoided in favour of using more direct, descriptive language - especially for screen readers - so I'd rather the link text be "view this package's readme on GitHub".
