### ISSUE TITLE
Documentation for primitive types

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#43]
Eg:
* http://pursuit.purescript.org/?q=Number
* http://pursuit.purescript.org/?q=String
* http://pursuit.purescript.org/?q=%5B%5D

It would be nice, particularly for beginners, for something to appear for these searches.
Is it possible to include documentation about these in the Prelude? Maybe by re-exporting them?

**Comment by paf31** [comment]
I think it might be best to just handle these as special cases, honestly. We can add a new "data source type" called "Primitive" or something.

**Comment by alexchandel** [comment]
This would be especially useful for `[]`.
