### ISSUE TITLE
Use GitHub API instead of directly using Git

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#49]
All we really need to do is

- Directory listings
- Reading files

which are covered by, for example:

- https://api.github.com/repos/purescript/purescript-arrays/contents
- https://raw.githubusercontent.com/purescript/purescript-arrays/master/bower.json

This way we can avoiding using Git on the command line, and only pull down the files we really need (`bower.json` and `src`)

**Comment by paf31** [comment]
In fact, [this](http://hackage.haskell.org/package/github-0.13.1/docs/src/Github-Repos.html#contentsFor) seems to do everything we need.

**Comment by hdgarrood** [comment]
We also need tags, but that package does the job with `tagsFor`.

I just tried this but `contentsFor` is failing with a JsonError because of a missing "encoding" key. I wonder if the github api has changed since this library was written...

**Comment by hdgarrood** [comment]
Ah, no, looking at the GitHub API https://developer.github.com/v3/repos/contents/ - the authors of that package haven't handled the case where the result is a directory properly.

**Comment by hdgarrood** [comment]
I've sent a PR that handles this case, so this issue is now blocked on jwiegley/github#95

**Comment by hdgarrood** [comment]
No longer an issue, since package authors submit their own packages now.
