### ISSUE TITLE
Remove comments which are not markdown comments

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#54]

**Comment by hdgarrood** [comment]
I'm not quite sure what the syntax for markdown comments is. Should this just be a case of doing `filter ("-- | " `isPrefixOf`)`?

**Comment by paf31** [comment]
I think the code already distinguishes markdown from non-markdown if I remember correctly. Right now it just dumps non-markdown in a `pre` tag.

**Comment by hdgarrood** [comment]
@paf31 I don't remember what this means - do you know if it still needs addressing?

**Comment by paf31** [comment]
Previously, any comments which were not Markdown blocks (indicated by pipes) were rendered using `pre` and `code` blocks and they looked pretty bad. I don't know if we still keep them.

**Comment by hdgarrood** [comment]
Ahh, ok. Now, we discard the whole lot unless every line has a pipe. That's easy to fix, but it needs to be fixed in the compiler unfortunately.

**Comment by paf31** [comment]
Nope, let's leave it like this then. The previous version was no better.
