### ISSUE TITLE
Search functions and instances as well as types and type classes

### ISSUE THREAD

**Issue by alexchandel** [purescript/pursuit#66]
For example, in addition to the datatype `Signal`, searching "Signal" should give me functions that have a  `Signal` in their type, as well as instances of `Signal`.

**Comment by paf31** [comment]
Related: https://github.com/purescript/pursuit/issues/2

**Comment by hdgarrood** [comment]
I worry that including instances would lead to a large number of uninteresting results. I think I'd rather just allow the user to decide which type they are interested in, go to the relevant package's own documentation (or psc-pages on pursuit - hopefully soon), and look at instances there.

**Comment by alexchandel** [comment]
An accumulation of instances is a definite possibility, but digging around shouldn't be necessary in a proper search interface. Often, I'm exploring as much as I'm zeroing in on a particular concept, so absconding away certain details only hurts me, since I'm not prepared to perform a depth-first search :P . Moreover, instances can be scattered across modules and packages, yet it's still informative to see know what implements what. And practically speaking, Pursuit probably isn't in danger of overwhelming results anytime soon: most searches I perform presently return 0 or 1 item. Should it become too much though, we could always add checkboxes for filtering types, classes, instances, and functions.

**Comment by hdgarrood** [comment]
> most searches I perform presently return 0 or 1 item

This is because the search is _very_ naive at the moment - I think just exact matches for names - and also because the database generation hasn't been working on the server for a while, so many of the listed packages' results don't show up at all.

If you look at [https://github.com/hdgarrood/purescript-sequences/blob/master/docs/Data.Sequence.md](this), for example, there are more instances than there are types and values put together.

Hoogle doesn't appear to include instances in results either; possibly it's worth trying to find out why?

In my experience, the only situations in which I care about instances are the ones when I am asking, "does type X have a Y instance?" or possibly "what instances does type X have?" I think Haddock-style docs are a better tool for answering these questions than Hoogle-style search is.

**Comment by alexchandel** [comment]
> This is because the search is very naive at the moment

Near-matches should probably be shown. But even with fuzzy searches, there aren't that many PureScript packages right now. On the order of 100? And many are sparsely populated.

> there are more instances than there are types and values put together.

That's not a problem. If it's absolutely necessary, just rank instances below types & type classes in search results.

> Hoogle doesn't appear to include instances in results either; possibly it's worth trying to find out why?

That's a deficiency of Hoogle. The Rust documentation for a given type class displays every instance known to rust-doc at the time. In fact, the plan is for crates.io to eventually provide cross-package searches. I guess if you've never had the ability you can't understand its usefulness, but trust me, it's valuable to know what implements what globally.

**Comment by hdgarrood** [comment]
I absolutely agree that it's valuable to know what implements what. But I don't think having instances appear in search results is a good way to achieve that. I'd much rather the flow be:

* Search for a type or type class
* The type/type class appears in results
* You click on it and are taken to Haddock style documentation, which then lists all instances that the type/type class has, together with the modules (and packages) that each instance is in.

> The Rust documentation for a given type class displays every instance known to rust-doc at the time.

Looking at the Rust documentation, it appears they take a similar approach to what I outlined above. The Search function doesn't appear to tell you anything about trait implementations directly, you have to go to a particular result's page first. For example:

* [Search results for "Debug"](http://doc.rust-lang.org/std/collections/struct.BTreeMap.html?search=Debug) - no information about trait implementations
* [Page for the "Debug" trait](http://doc.rust-lang.org/std/fmt/trait.Debug.html) - includes list of all implementations.

**Comment by hdgarrood** [comment]
The flow I described has been implemented. Now that we're using Hoogle for searches, you could suggest that instances appear in search results there if you wanted.
