### ISSUE TITLE
Fetch search results via AJAX

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#69]
At the moment, since pursuit is completely server-side, you get an ugly white flash while the results are loading. It would look nicer if the search page itself only needed to load once, and then results could be fetched via AJAX and rendered on the client side.

This could also be a good opportunity to investigate things such as:

* Sharing data between Haskell and PureScript (purescript/purescript#891)
* Working out how to integrate PureScript code compilation into a Haskell project. We could either compile PureScript during `cabal build` (I managed to hook into cabal like this once with Fay, I think) or do it inside the actual server executable on startup.

**Comment by paf31** [comment]
:+1:

**Comment by hdgarrood** [comment]
Search results are rendered on the server side too now.

**Comment by hdgarrood** [comment]
Oh wait, I didn't read this very carefully. Although - even though search results are rendered on the server, there is no longer an ugly white flash. I'm not sure why that is, but I think it's ok to leave this closed.

**Comment by paf31** [comment]
Even if we don't use it internally, I think it miht be nice to extract a JSON API (later).

**Comment by hdgarrood** [comment]
Agreed. There's already a data type for this (`Handler.Hoogle.HoogleResult`) so this would just be a case of writing a ToJSON instance and reading the Accept header inside `/search` to decide how to respond
