### ISSUE TITLE
Rank search results

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#7]
Searching for `flip` doesn't even show `flip` because there are so many instances for the `Flip` type constructor and we only pick the top 20. We should sort the results based on relevance.

**Comment by alexbiehl** [comment]
We faced the same issue in Hayoo. Take a look at 
https://github.com/hunt-framework/hayoo/blob/master/hayooIndexer/src/Hayoo/PackageRank.hs

It ranks a package by how many packages depend on it (transitively). You can use the ranks to boost types and functions.

**Comment by hdgarrood** [comment]
Oh, awesome - thank you!

**Comment by hdgarrood** [comment]
Resolved now that we switched to using Hoogle for searches.
