### ISSUE TITLE
Hoogle Integration

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#89]
@hdgarrood I'll create issues for GSOC items which don't have issues yet.

What's left to get a first version of Hoogle integration in place?

**Comment by hdgarrood** [comment]
I'm currently waiting for feedback from Neil Mitchell on the latest version of the Hoogle files that Pursuit produces, so I'm not exactly sure what the next steps should be right now (although, I can probably work it out on my own if need be).

**Comment by paf31** [comment]
Maybe prioritize #90 or improved error pages then?

Once the file output is nailed down, it's just a case of calling [`mergeDatabase`](http://hackage.haskell.org/package/hoogle-4.2.41/docs/src/Hoogle.html#mergeDatabase) and friends, right? If so, it should be possible to make progress even if the file output isn't finalized, no?

**Comment by hdgarrood** [comment]
Yeah, something along those lines. And yes, I think it should be possible to make progress if the file output isn't finalized. I'll start looking at this soon.

**Comment by hdgarrood** [comment]
https://twitter.com/hdgarrood/status/617120379308523521
