### ISSUE TITLE
Add Package List

### ISSUE THREAD

**Issue by paf31** [purescript/pursuit#90]
The front page should ideally show a list of all registered packages.

**Comment by michaelficarra** [comment]
A tree would be even better.

**Comment by hdgarrood** [comment]
How would a tree work?

**Comment by hdgarrood** [comment]
0b98ba26f1029f587a1cdd532392b3bcf67be307 adds a list, but I'd like to hear more about @michaelficarra's suggestion before closing.

**Comment by paf31** [comment]
Thanks, I've update the [site](http://new-pursuit.purescript.org/).

**Comment by michaelficarra** [comment]
I was thinking a tree to represent dependency relationships, but realised it would be a DAG, and that would be a bit unruly to try to render.
