### ISSUE TITLE
Some thoughts on caching

### ISSUE THREAD

**Issue by hdgarrood** [purescript/pursuit#94]
Are we more interested in avoiding transmission of the same HTML across the network lots of times, or avoid generation of the same HTML lots of times? One thing that's worth noting here is that the readme is fetched via GitHub's API, so we should definitely avoid requesting that every time, even if we are using 304 responses to avoid sending it over the network.

The current caching system only deals with avoiding generation of the same HTML lots of times, so if we also want to avoid sending it across the network lots of times, it needs replacing / amending.

If we use the nginx method, I think we should tell it that it's only allowed to cache 200 responses. This is because some 302 responses should not be cached: in particular, after you upload a new version of a package, you get sent to `/package/$packagename`, which redirects you to the newest version using a 302 response. If we cache this response, then after uploading a new package, you'll be sent to the previous version, which would be quite confusing.

Also, if we use the nginx method, we'll need to tell it to ignore the Set-Cookie header, using `proxy_cache_ignore_headers` - usually it will refuse to cache anything with a Set-Cookie header, and all of our responses have those (they is necessary for timed session expiry, since we use client side sessions).

Another issue to consider is how it decides what response headers to send back to the client. We certainly don't want it to cache and resend the same set of response headers every time, as this would include session cookies.

Given that the vast majority of stuff is cacheable &mdash; I'm pretty sure it's everything apart from `/upload` and `/oauth/callback` &mdash; perhaps we can avoid all of the header issues by serving the non-cacheable stuff from a different domain name? Then we can forget about authentication, sessions, etc for the rest of the app, where they're not necessary and just get in the way.

**Comment by paf31** [comment]
I was thinking that a static caching scheme would work, where we just create a HTML file on disk after upload, and then let nginx do the work of caching it. We could regenerate it if we needed to (if the template changed, or whatever). The front page for each package would then be a simple redirect, and would not be cached. We'd also have to extract a few small pieces like the version selector into JavaScript.

I appreciate it's quite different from the current approach though, so I don't mind if you'd prefer to leave this out of GSOC, but I do like it for its simplicity.

**Comment by hdgarrood** [comment]
Ah, ok, yeah that makes sense. Just checking I understand - so the yesod part would never even see a request like `GET /packages/purescript-arrays/0.4.0/docs/Data.Array`, it would be handled entirely inside nginx?

**Comment by hdgarrood** [comment]
This system seems to be working on my machine, with the following configuration:
```
server {
    listen 80;
    server_name localhost;

    location / {
        root /home/harry/documents/code/pursuit/data/cache;
        try_files $uri/index.html $uri/index.json $uri/index.svg @backend;
    }

    location @backend {
        proxy_pass http://localhost:3000;
    }
}
```

Not only can we now avoid generating the same HTML repeatedly, but it's also sending ETag and Last-Modified headers and using 304 responses where suitable (I guess nginx does this by default?)

**Comment by hdgarrood** [comment]
Resolved.
